### ISSUE TITLE
Fedora/EPEL Updates Tracking

### ISSUE THREAD

**Issue by thiell** [cea-hpc/clustershell#123]
''Fedora and EPEL Updates information tracking ticket.
''
Original Fedora Package Collection submission ticket: #108

**Comment by degremont** [comment]
@thiell is this ticket still relevant?

EPEL updates were done smoothly since the beginning. Versions 1.6, 1.7 and 1.7.1 are not listed there but where pushed to Fedora/EPEL in a timely manner.

**Comment by thiell** [comment]
Yep, this is not needed anymore.
