### ISSUE TITLE
Need improved package installation for pip

### ISSUE THREAD

**Issue by thiell** [cea-hpc/clustershell#170]
Today it is possible to install ClusterShell with pip within virtualenv, or not.

pip install info: http://www.pip-installer.org/en/latest/installing.html

However, the python package doesn't create any `clush.conf` nor `groups.conf` config file (eg. in `/etc/clustershell`).

```
[root@star ~]# python virtualenv.py pip_env
New python executable in pip_env/bin/python
Installing setuptools...........................done.
Installing pip.....................done.
[root@star ~]# . pip_env/bin/activate
(pip_env)[root@star ~]# pip search clustershell
ClusterShell              - ClusterShell library and tools
(pip_env)[root@star ~]# pip install clustershell
Downloading/unpacking clustershell
  Downloading clustershell-1.5.1.tar.gz (159Kb): 159Kb downloaded
  Running setup.py egg_info for package clustershell
Installing collected packages: clustershell
  Running setup.py install for clustershell
    changing mode of build/scripts-2.6/clubak from 644 to 755
    changing mode of build/scripts-2.6/clush from 644 to 755
    changing mode of build/scripts-2.6/nodeset from 644 to 755
    /root/pip_env/bin/python -O /tmp/tmpopn5pr.py
    removing /tmp/tmpopn5pr.py
    changing mode of /root/pip_env/bin/clubak to 755
    changing mode of /root/pip_env/bin/nodeset to 755
    changing mode of /root/pip_env/bin/clush to 755
Successfully installed clustershell
Cleaning up...
(pip_env)[root@star ~]# clush --version
clush 1.5.1
(pip_env)[root@star ~]# nodeset -l
nodeset: Unknown group source: "<default>"
```

We need to find a way to put configuration files in some generic place. I don't know where yet.

**Comment by thiell** [comment]
Ok bringing back this old ticket for 1.7 as we need `NodeSet` to work better from `pip install --user clustershell`.

There are many threads on stackoverflow about the best way to install configuration files (or data files) with distutils/setuptools. After reading all of thoses, it seems there isn't any ideal solution. Some solutions are just crazy...

I found out that the following thread is useful as it explains the differences between distutils, setuptools, etc. and why these tools don't (want to) install files anywhere like in /etc.

http://stackoverflow.com/questions/10456279/python-setuptools-how-to-include-a-config-file-for-distribution-into-prefix

Back to this ticket, I guess I found a way to make it work without having to do too many changes to current packaging.

What do we want in 1.7?
* RPMs packaging just as before
* an user should be able to install clustershell using `pip install --user clustershell`
 * `pip install --user clustershell` will install clustershell to ~/.local/ (by default) along with other Python pip programs
 * user-specific clustershell configuration files should be supported by setting an environment variable. With pip, they will be installed in `$prefix/etc/clustershell` or `~/.local/etc/clustershell` for default pip install. As a side node, with ClusterShell 1.6, pip doesn't fail but no configuration files other than the ones in `/etc/clustershell` are supported (because it is hardcoded !).

So my plan for 1.7 is to work on a patch that will:
* introduce clustershell configuration files as `data_files` in setup.py. As root, the default installation path is $prefix/etc, that is `/usr/etc`, but we don't care! We just want pip as user to work. Indeed, this first fix makes pip installing config files in `~/.local/etc/` so that's a first step.
* modify clustershell.spec as `python setup install --root %{buildroot}` will install config files in `%{buildroot}/usr/etc`. My proposal is to do a `mv %{buildroot}/usr/etc %{buildroot}/%{_sysconfdir}` just after. And that seems to work! And another good thing, we don't need anymore the install steps of config files in the spec file...
* add an environment variable to override the default config file directory (if absent, we will use `/etc/clustershell` of course). If somebody has an idea to avoid this env variable, please tell me.
* add a specific documentation paragraph to explain how to use clustershell as an user with pip and an example of using `NodeSet` to parse `$SLURM_NODELIST` in a batch script.

**Comment by degremont** [comment]
* Config files using environment variable is tracked by #111 
* User custom files should be stored in ``.config`` I think (http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html)  (Probably ``.config/clustershell``)

But what's the matter with having no default config file ? User will have to setup its own group sources anyway.

**Comment by thiell** [comment]
Well you need at least the config files to appear somewhere, as an example? Today they are not provided through pip. We could also provide them through /usr/share as a doc files, that could be another solution...

**Comment by thiell** [comment]
for `.config/clustershell`, I'm not sure it's easily doable through pip/setuptools, as it is outside an install prefix.... I wonder if that freedesktop spec is really used...

**Comment by kcgthb** [comment]
XDG stands for "X Desktop Group", I'm not sure its standards are relevant for ClusterShell...
I vote for `~/.local/{bin,etc,lib}`

**Comment by degremont** [comment]
home directory content is a mess. For decades softwares added their own ``~/.abc`` directory making your own home directory a endless list of subdirectories. ``ls -al ~/`` could be really awful.

Based on this, people tried to promote a new way to organize this. As they also realized that directory content was a mix a config files, temporary data, etc... they proposed several new directory: one for config files (``~/.config/``), one for user data (``.local``), one for cache (``.cache``). That way, you can easily wipe .cache as it has no important data, .local should be backup, .config could be shared if you want between several machines by example. 

There is not reason to say bah ``.config`` is from XDG, we should not use it, as ``.local`` is also a XDG standard. And this is really used, I already have 39 subdirectories in ``.config`` on my laptop.

Practically, this was pushed by freedesktop originally, but this does not means other should not use it. We do not want to have ``.local_for_gui``, and  ``.local_for_systool``, ``.local_for_games``. This makes no sense.

* ``/usr/share/clustershell/`` -> ``~/.local/share/clustershell/``
* ``/etc/clustershell/`` -> ``~/.config/clustershell/``

**Comment by thiell** [comment]
Hello :)

I won't agree without any beer... the problem is that you still have your home directory as a "base" directory which can be a mess. I prefer the pip way (without virtualenv), that creates a new base directory according to PEP-370 https://www.python.org/dev/peps/pep-0370/, about `.local`:

_It's located inside the user's home directory. The user site and use config directory are inside the base directory._

BTW it's named `.local` but it's not XDG compliant, and more people use pip than XDG compliant software in HPC I guess...

**Comment by thiell** [comment]
Hrm, according to this PEP, we should put config files in `~/.local/lib/python2.6`-like dir... sounds a bit weird

**Comment by degremont** [comment]
I think you are misreading this PEP. It does not say you should put your config files there. Only python "data" and it means packages, modules, etc... Same kind of info that would be in ``/usr/lib/python/...``

But I'm glad you mention it as:
``
On Unix ~/.local was chosen in favor over ~/.python because the directory is already used by several other programs in analogy to /usr/local 
``
With 2 references on:
* [7] Suggestion of ~/.local/ http://permalink.gmane.org/gmane.comp.python.devel/90925 
* [11] freedesktop.org XGD basedir specs mentions ~/.local http://www.freedesktop.org/wiki/Specifications/basedir-spec 

So Python is in-line with XDG! :)

**Comment by thiell** [comment]
So if `.local` is a basedir, I wonder why are config files put in `.config` and not `.local/config` or `.local/.config` (as some software do)?

But well, indeed, theoretically I agree with you that `.config/clustershell` would be the best. My problem is more pragmatic, I didn't find a way to install the config files with setuptools if they are put outside the basedir (or prefix)... unless doing something dirty. :) I will re-check this point ASAP.

**Comment by thiell** [comment]
Ok so new proposal:
* I fix #111 with `$XDG_CONFIG_HOME` (`.config/clustershell`) so that when ClusterShell is installed on the system, an user can override the configuration by putting config files there. Also we support `.config/clush.conf` etc.
* When installing with pip, default config files will be installed in `.local/etc/clustershell` but we could advise the user to use `.config/clustershell` or also make `.local/etc/clustershell` as a failback config dir? that remains to be checked in details but that's the idea

Does it sound good for you?

**Comment by kcgthb** [comment]
>  And this is really used, I already have 39 subdirectories in .config on my laptop.

Exactly, on your *laptop*. :)
On a server, unless you launch Gnome-based graphical sessions as root (boo! you should never do that, you know?), `/root/.config` is pretty empty.

**Comment by degremont** [comment]
>  On a server, unless you launch Gnome-based graphical sessions ~/.config is pretty empty.

I thought we were working on fixing *user* experience. CS is surprisingly used a lot in user mode (at least, more than we were expecting, but that's good news!)

**Comment by thiell** [comment]
https://review.gerrithub.io/245269/

**Comment by thiell** [comment]
Online test rtfd recently updated with gerrit patch proposed changes:

* http://clustershell-test.readthedocs.org/en/latest/
