### ISSUE TITLE
RangeSetException import from NodeSet module is broken in v1.6

### ISSUE THREAD

**Issue by degremont** [cea-hpc/clustershell#189]
Since ClusterShell v1.6

```python
from ClusterShell.NodeSet import RangeSetException 
```
is broken

This is working perfectly in previous version.

For compatibility sake, it is a good idea to fix this in the next release.

**Comment by thiell** [comment]
After almost 3 years, I don't think the compatibility argument is still valid. ;-) So what should we do ?
Probably we should be able to import all NodeSet/RangeSet based exceptions from NodeSet as they may be raised when using this module...

BTW, I noticed that we added a `__all__` in RangeSet module. Maybe we should do the same for the NodeSet module, including some classes from RangeSet like its exceptions ? Even if it's not a good thing to use wildcard imports, it would still help the user to determine all classes that can be imported without risk.

**Comment by degremont** [comment]
> After almost 3 years, I don't think the compatibility argument is still valid. ;-) So what should we do ?

Hum... The ticket was opened on the current release... 1.6 branch is still the latest one ;)

I think we should import RangeSet Exceptions in NodeSet namespace.

``__all__ `` is only there to prevent class user to importing things they should not. In other words, this limits export scope and avoid using some private classes. (we should have been prefixed by _)
