### ISSUE TITLE
Problem running command in tree mode

### ISSUE THREAD

**Issue by spulvera** [cea-hpc/clustershell#207]
Hello,

I did some tests using clush in tree mode. My tree is quite simple: 1 admin node, 2 gateways and 2 childs by gateway:

My configuration file:

    admin:gw[0-1]
    gw0:target[0-1]
    gw1:target[2-3]

Test 1:
When I want to run a command (i.e. /bin/hostname) on target[0-4], everything is OK.

Test 2:
When I want to run the same command on target[0-4], I should have an error message as in ssh mode because target4 is unreachable. I got the same result as the Test 1 and no error message.

Test 3:
When I want to run the same command on target[0-3] and either the admin node or a gateway, I got the same result as the Test 1 and no print for the extra node. The fanout is larger than the number of wanted targets.

**Comment by thiell** [comment]
Actually I don't understand the problem at all.
