### ISSUE TITLE
Error parsing configuration file with TopologyParser

### ISSUE THREAD

**Issue by spulvera** [cea-hpc/clustershell#208]
Hello,

There is a bug in the configuration file parsing using TopologyParser class. I did the test with 2 configuration files:

1/ test_topo.conf:

    [Main]
    CLUSTERSHELL-CENTOS6-1:CLUSTERSHELL-CENTOS6-[2-3]
    CLUSTERSHELL-CENTOS6-2:CLUSTERSHELL-CENTOS6-[4-5]
    CLUSTERSHELL-CENTOS6-3:CLUSTERSHELL-CENTOS6-[6-7]

2/ test_topo_detailed.conf:

    [Main]
    CLUSTERSHELL-CENTOS6-1:CLUSTERSHELL-CENTOS6-2,CLUSTERSHELL-CENTOS6-3
    CLUSTERSHELL-CENTOS6-2:CLUSTERSHELL-CENTOS6-[4-5]
    CLUSTERSHELL-CENTOS6-3:CLUSTERSHELL-CENTOS6-[6-7]

Here is my python test script:

    parser = TopologyParser()
    parser.load("~/.clustershell/tests/test_topo.conf")
    myTree = parser.tree("CLUSTERSHELL-CENTOS6-1")
    print "Tree:\n", myTree
    
    parser1 = TopologyParser()
    parser1.load("~/.clustershell/tests/test_topo_detailed.conf")
    myTree1 = parser1.tree("CLUSTERSHELL-CENTOS6-1")
    print "Tree1:\n", myTree1

And the execution result:

    Tree:
    CLUSTERSHELL-CENTOS6-1
    `- CLUSTERSHELL-CENTOS6-[2-3]

    Tree1:
    CLUSTERSHELL-CENTOS6-1
    |- CLUSTERSHELL-CENTOS6-2
    |  `- CLUSTERSHELL-CENTOS6-[4-5]
    `- CLUSTERSHELL-CENTOS6-3
       `- CLUSTERSHELL-CENTOS6-[6-7]

**Comment by thiell** [comment]
The nD problem has been solved for a while, but the script is still blocking as of 1.6.92.
It looks like it's fixed by RangeSet copy changes in https://review.gerrithub.io/238825/
