### ISSUE TITLE
Problem executing sequentially two tests using a WorkerTree

### ISSUE THREAD

**Issue by spulvera** [cea-hpc/clustershell#210]
Hello,

While excuting two consecutives tests using the command propagation on tree mode, tasks and workers are not completely cleaned, so the command does not run well : nothing executed in the second test.

Call the functions "task_cleanup" and "task_terminate" solves the problem in most cases..

**Comment by thiell** [comment]
Multiple executions work fine now. I tested scripts using both sequential and event-based models. However, when testing I found another bug (#306) which is not directly related to this one.
