### ISSUE TITLE
Provide the  "User and Programming Guide" in Markdown

### ISSUE THREAD

**Issue by zoobab** [cea-hpc/clustershell#218]
Hi,

Would it be possible to publish the "Provide the  "User and Programming Guide" in another format more easy to read then PDF, for example Markdown?

Best,

**Comment by thiell** [comment]
We won't do .md for the guide. An online doc for the Python API would be nice, but for now we stay with LaTeX as the living reference document for ClusterShell, and hopefully some info, tips and tricks, etc. on the wiki. Docs contributions are also welcomed.

**Comment by thiell** [comment]
We plan to provide easy to read docs, not in .md but will be easily available.
Ticket for this task is #262. Hope you will like it.
