### ISSUE TITLE
To support pdsh/dsh explicit host file use case

### ISSUE THREAD

**Issue by haiwu** [cea-hpc/clustershell#235]
Right now clush does not support explicit host file use case, which is the most useful cases for daily sysadmin tasks. Most of the time you just need to run command against some random hosts, rather than those files in preconfigured host groups in 'groups' file. The workaround is to do this:

`clush -w $(cat host_file | paste -d, -s) cmd`

But this is too much typing. It should work if clush really wants to replace pdsh/dsh, otherwise there is no way for people to fully switch to use clush instead of pdsh later.

**Comment by thiell** [comment]
https://review.gerrithub.io/250102
