### ISSUE TITLE
Drop support of Python 2.4 and 2.5 to prepare Python 3

### ISSUE THREAD

**Issue by degremont** [cea-hpc/clustershell#239]
Python 3 will be default Python version for Fedora 22. This does not means Python 2 tools won't work any more but it will become more difficult to support them.

We should start working toward supporting Python 3. The first step for that is to stop supporting Python 2.4 and 2.5. 
In RHEL world, Python 2.6 is there since RHEL 6.0. Fedora supports Python 2.6 since ages. Debian stable uses Python 2.7 and was previously already supporting Python 2.6. Same for Ubuntu. Arch, Gentoo are fine too.

We should removing all deprecated stuff from these versions to come closer to Python 3 syntax.
Here is short list of things to start with:
- except syntax (`except Exception as exp`)
- all classes must inherit from `object`

`pylint --disable=all --enable=old-style-class  ClusterShell/`
- drop `has_key()`
- relative import should be fine (I don't think we are using them. Pylint normally complains if we do so)
- several methods now return an iterator instead of a list. This could easily trigger bugs, but hard to catch them.
- unittest compability (see 2to3)

An interesting documentation: https://docs.python.org/3.3/howto/pyporting.html
https://docs.python.org/3/library/2to3.html#2to3fixer-except
http://python-modernize.readthedocs.org/en/latest/fixers.html

Strings management will be a pain. I think this should be done at the end.
Prefer making small patches to do this incrementally and not a big patch for everything.

**Comment by thiell** [comment]
Another thing to look at is the use of `super()`.

As for Python 3, not that I do not work on it... :), but it's not yet the default on Fedora 22 (I have 2.7.10 right now on a fresh install).

**Comment by thiell** [comment]
We could use [bytes](https://www.python.org/dev/peps/pep-0358/) instead of str whenever possible. It is available in Python 2.6 as an alias of str.

**Comment by degremont** [comment]
Using bytes should probably be done when fixing #22 and #309

**Comment by SyntaxRules** [comment]
+1 For python 3 support

**Comment by degremont** [comment]
This ticket looks very close to be finished. Just need to update README & docs to announce we only support from Python 2.6 now, and we can close it.
