### ISSUE TITLE
Need an output format option for expand option (-e)

### ISSUE THREAD

**Issue by PhilippeGregoire** [cea-hpc/clustershell#246]
It will be nice and usefull  to have the possibility with expand option to specify an output format as
-O "<string>" where all %s in <string> will be replaced by the node name. This option should be 
also combined with -S <sep>

Example:
```
$ nodeset -e @io -O "/ClusterLogs/Console/%s.log" 
/ClusterLogs/Console/foo123.log /ClusterLogs/Console/foo123.log

$ grep RMDA $( nodeset -e @io -O "/ClusterLogs/Consoles/%s.log"  )

$ grep $(  nodeset -e @io -O "%s-ib0" -S '|' ) /var/log/syslog
```

**Comment by kcgthb** [comment]
Mon cher Fifi,

I feel like there are so many external tools to handle strings manipulation that it would be ineffective to add such formatting capabilities into ClusterShell.

What about this, for instance?
```shell
$ nodeset -e @io | sed 's:\([^ ]*\):/ClusterLogs/Console\1.log:g'
/ClusterLogs/Consolefoo123.log /ClusterLogs/Consolefoo234.log

$ nodeset -S '|' -e @io | sed 's:\([^|]*\):\1-ib0:g'
foo123-ib0|foo234-ib0
```

**Comment by thiell** [comment]
Fifi insisted so much that I decided to be kind to older sysadmin :smile: 

```bash
$ nodeset -O "/ClusterLogs/Console/%s" -e foo[123-124]
/ClusterLogs/Console/foo123 /ClusterLogs/Console/foo124

$ nodeset -S '|' -O "%s-ib0" -e foo[123-124]
foo123-ib0|foo124-ib0
```

Some other reasons why I accepted this change:
* the code needed to implement it is very short
* the `--separator` option is already an existing output formatting option, so `--output-format` / `-O` will just complete it to allow a wide range of output displays (both are needed to do advanced formatting)

Just be careful with `nodeset` to use options like `--separator` (or `-S`) and `--output-format` (-or `-O`) **before** any nodeset inputs (`@io` in your example, or `foo[123-124]` in mine). Your examples won't work as is.
