### ISSUE TITLE
recently introduced new options --ssh_path, --scp_path, --ssh_options and --scp_options do not work from commandline

### ISSUE THREAD

**Issue by getreu** [cea-hpc/clustershell#247]
As part of my recent pullrequest #245 the above options had been modified respectively introduced. When I tested the options I defined them in the config file and everything worked well. 
Now I tried to submit them on the command line and they were not understood!

This possibility is important because users will use sshpass usualy once in the beginning of a session to append their certificates to the remote authorized_hosts file. Once this is done sshpass is not needed any more as clush can connect the usual way (which is much faster). In order to not be forced to modify the configuration file just for this one and first connect, users should be enabled to pass   --ssh_path, --scp_path, --ssh_options and --scp_options on the command line.

My pull request "support for ssh_pass added #245" adds some code for this but it seems it is not complete. I do not have time now, maybe someone could have a look what is missing. I am sure it is just a small thing.

**Comment by thiell** [comment]
Duplicate/fixed in #248
