### ISSUE TITLE
Tree mode doesn't work when the hostname of a gateway is different from the name used to contact it.

### ISSUE THREAD

**Issue by AdrienDebrie** [cea-hpc/clustershell#250]
When the hostname of a machine used as a gateway is not the same as the name used to contact it, it is not possible to use the tree mode.

```
$ cat /etc/clustershell/topology.conf
[Main]
root : gidc0-mn
gidc0-mn : mexico[0-4,21]
$ ssh gidc0-mn hostname
gidc0
$ clush -w mexico3 hostname
clush: TREE MODE: Invalid admin node: gidc0
rc=1
$
```

The GatewayChannel.hostname is not found in the topology received. A RouteResolvingError is raised by the associated PropagationTreeRouter.

Is there a way to avoid this (other than playing with ssh aliases)?

**Comment by degremont** [comment]
This should be fixed add a new feature. A node mapping for gateways. It should be possible to define a source name as a mapping use to get the gateway network host, based on gateway name. This should be a simple patch.

**Comment by degremont** [comment]
Possible implementations:

Add to topology.conf a new section 

```
[gateways]
name_mapping: cw-gw
```

In Propagation or Task.shell, when the gateway name is know, try to map it using the source name set in this new option if set.

**Comment by thiell** [comment]
For deep trees (multi-hops gateways), it can be more tricky. Either we could:
- propagate a pre-generated node mapping from the root node (only of all gateway nodes),
- or just propagate the group source name (but in that case, groups.conf with that source name must be configured on all gateways, not sure I like that).

**Comment by degremont** [comment]
If we want to be coherent with current code, we should propagate the pre-generated node mapping, like we do with the tree.

The second possibility is to propagate no information and, locally on each gateway, looks for a local configuration (both topology.conf and gateway node mapping). This solution could handle all use cases but is more complex to deploy a

**Comment by thiell** [comment]
Yeah I agree, option 1 seems the best, option 2 is too error prone...

**Comment by thiell** [comment]
Well I pick option 3!

https://review.gerrithub.io/250489

**Comment by thiell** [comment]
Finally, option 4 is _the one_: node/host/alias/whatever present in topology.conf and used to actually connect to to remote gateway (using ssh, by default) is sent to the gateway itself and then used (and trusted) by the gateway instead of a system hostname check...
