### ISSUE TITLE
NodeSet should support unicode

### ISSUE THREAD

**Issue by wilfriedroset** [cea-hpc/clustershell#251]
Hi,

Is it plan to support unicode ? The error message is quite clear:

```
>>> NodeSet(u"node1")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/ClusterShell/NodeSet.py", line 909, in __init__
    self.update(nodes)
  File "/usr/lib/python2.7/site-packages/ClusterShell/NodeSet.py", line 1173, in update
    nodeset = self._parser.parse(other, self._autostep)
  File "/usr/lib/python2.7/site-packages/ClusterShell/NodeSet.py", line 689, in parse
    raise TypeError("Unsupported NodeSet input %s" % type(nsobj))
TypeError: Unsupported NodeSet input <type 'unicode'>
>>> NodeSet(str(u"node1"))
<ClusterShell.NodeSet.NodeSet object at 0x7f169eae5ed0>
```

It would be great of clustershell to support it so we can create nodeset seamlessly from string or unicode.

**Comment by degremont** [comment]
There is no plan for that for now, but this issue could easily be workaround simply converting strings to str object before sending them to NodeSet. I do not really consider hostnames with unicode characters as a real use case for now :)
This is very easy to workaround, this is low priority for us for now.

**Comment by thiell** [comment]
In Python 3 strings are sequences of unicode characters, maybe it's something to look at more closely when it's time to support Python 3...

If your strings are coming from a misc library or Web framework, anyway it's better to filter them before passing them to NodeSet. Some characters are handled as special characters in NodeSet syntax.

**Comment by thiell** [comment]
Hey actually, it's not that bad:

```
$ nodeset -e ૐ[1-9]
ૐ1 ૐ2 ૐ3 ૐ4 ૐ5 ૐ6 ૐ7 ૐ8 ૐ9
```

Finally, I think I will remove this explicit typecheck in ParsingEngine.parse() which is not so Pythonic and give it a try for 1.7...

**Comment by thiell** [comment]
Ok finally I didn't remove the typecheck, otherwise NodeSet will accept almost any Python objects, but I found out that using typecheck against basestring is more suited here (but it's not compatible with Python3). It allows unicode string that can be easily converted to ascii to be used.

Also I don't fully understand why my previous example with nodeset CLI is working actually...

https://review.gerrithub.io/251240
