### ISSUE TITLE
Incorrect "in progress" summary when mixing direct connections and connections through gateways

### ISSUE THREAD

**Issue by martinetd** [cea-hpc/clustershell#257]
clush doesn't count nodes it connects directly to in the short summary display

Easy to reproduce:
```
 # clush -bw direct[1-2],remote[1-8] sleep 10
 clush:  2/10 gw 1
 clush: interrupt (^C to abort task)
 clush: in progress(3): direct[1-2],gw1
 clush: [tree] open gateways(1): gw1
 clush: [tree] in progress(8) on gw1: remote[1-8]
```
The count corrects itself when all gateway tasks finish e.g.
```
 # clush -bw direct[1-2],remote[1-8] '[[ $(hostname) = direct* ]] && sleep 10'
 clush:  8/10
 clush: interrupt (^C to abort task)
 clush: in progress(2): direct[1-2]
```
We can't just add cnt += len(self.task._engine.clients() (in Clush.py) because gw1 is an active client (listed in "in progress") even if there's no task on it, so we'd end up with e.g. -1/10 done

Would it be possible to not count "pure" gateways in active clients?

**Comment by martinetd** [comment]
Actually since a worker on a gateway will open another connection anyway, the gateway is counted twice and this seems to work:

```python
diff --git a/lib/ClusterShell/CLI/Clush.py b/lib/ClusterShell/CLI/Clush.py
index 2efeb04..5a7c3a1 100755
--- a/lib/ClusterShell/CLI/Clush.py
+++ b/lib/ClusterShell/CLI/Clush.py
@@ -323,7 +323,7 @@ class RunTimer(EventHandler):
             act_targets = NodeSet()
             for gw, (chan, metaworkers) in self.task.gateways.iteritems():
                 act_targets.updaten(mw.gwtargets[gw] for mw in metaworkers)
-            cnt = len(act_targets)
+            cnt = len(act_targets) + len(self.task._engine.clients()) - len(gws)
             gwinfo = ' gw %d' % len(gws)
         else:
             cnt = len(self.task._engine.clients())
```

**Comment by thiell** [comment]
Thanks for reporting! I didn't have time to check yet but that sounds a great find. Do you want to push it to gerrithub ? There are no min lines in patches ;-)

**Comment by martinetd** [comment]
Has been since yesterday. Register to notifications already ;)
https://review.gerrithub.io/#/c/238882/

**Comment by thiell** [comment]
Oops! Ok I registered... sorry about that!
