### ISSUE TITLE
Node groups: multiple sources single flat file

### ISSUE THREAD

**Issue by thiell** [cea-hpc/clustershell#258]
By default, clustershell provides an example of single flat file group source configuration `/etc/clustershell/groups` and its associated map, list and all upcalls.
Even if it is an example configuration file, a lot of people are using it, using provided upcalls as is. Indeed, it is very convenient to have a single cluster configuration file, and for this, sysadmins shouldn't need to write their own scripts after installing clustershell.

Sometimes  `/etc/clustershell/groups` is rich, especially on heteregenous clusters with a lot of different system details about each node, like for example:
- location like rack position
- physical (cpu type, gpu types, memory size...)
- vendors and hw models, useful info for firmware update
- ownership of nodes and partitions (for multi owners clusters)
- infrastructure (pdu, network and interco switches)
- functional (compute nodes, storage nodes, service nodes, etc.)

As you can expect, sometimes this information is arranged with the use of groupname prefix (eg. rack..., cpu..., gpu..., vendor..., etc.). It looks like a perfect fit for the use of group sources. But with the example provided, users cannot easily arrange this info into different group sources without breaking the single flat file concept.

I propose a simple fix to address this and improve clustershell default groups config by:
- allowing the use of a comma-separated list of group source names in `groups.conf` sections
- adding a new `$SOURCE` variable, valid in all upcalls, that references the current group source name
- add an example of use in `groups.conf` shipped with clustershell

Example of new section in `groups.conf` (upcalls use sed address ranges to select the section used):
```ini
# EXAMPLE 2: multiple sources single flat file "group: nodeset" with sections
# Note that here $SOURCE is replaced with 'default', 'racks' and 'cpu'.
[default,racks,cpu]
map: sed -n '/\[$SOURCE\]/,/^\[/ s/^$GROUP:\(.*\)/\1/p' /etc/clustershell/groups2
all: sed -n '/\[$SOURCE\]/,/^\[/ s/^all:\(.*\)/\1/p' /etc/clustershell/groups2
list: sed -n '/\[$SOURCE\]/,/^\[/ s/^\([0-9A-Za-z_-]*\):.*/\1/p' /etc/clustershell/groups2
```

Example of new included file `groups2` (ideas for another name welcomed):
```ini
# Example of group flat file with multiple group sources.
# A way to parse it is to use sed address ranges.
# Please see also groups.conf
#
[default]
adm: example0
io: @rack:rack2,example2
compute: @rack:rack3
all: @adm,@io,@compute

[racks]
rack1: example[0,2]
rack2: example[4-5]
rack3: example[32-159]
# other groups in same source may be referenced without the "source:" prefix
all: @rack[1-3]

[cpu]
ivy: example[32-63]
# groups from other sources must be prefixed with "source:"
hsw: @default:compute!@ivy
```

In practice, the result is:
```bash
$ ./nodeset.py --groupsources
default (default)
racks
cpu

$ ./nodeset.py -ll
@adm example0
@all example[0,2,4-5,32-159]
@compute example[32-159]
@io example[2,4-5]

$ ./nodeset.py -s racks -ll
@racks:all example[0,2,4-5,32-159]
@racks:rack1 example[0,2]
@racks:rack2 example[4-5]
@racks:rack3 example[32-159]
```

Feedback are welcomed!

**Comment by thiell** [comment]
Implementation proposition: https://review.gerrithub.io/239589

**Comment by kcgthb** [comment]
+1!
For `groups2`, I'd suggest `cluster_groups`. Or maybe `hierarchical_groups`?

**Comment by degremont** [comment]
On our production clusters we achieve something similar ''without writing our own scripts''.
Considering the base config file ``/etc/clustershell/groups.conf.d/local.conf``:
```
[local]
map: sed -n 's/^$GROUP:\(.*\)/\1/p' /etc/clustershell/groups.d/local.conf
all: sed -n 's/^all:\(.*\)/\1/p' /etc/clustershell/groups.d/local.conf
list: sed -n 's/^\([0-9A-Za-z_-]*\):.*/\1/p' /etc/clustershell/groups.d/local.conf
```

Everytime we want a new source, we simply copy this file with a new name and with a new data file.
This is very easy to do with Puppet. All sources are independent.
If you put everything in the same config file, that's a pain for management.

However, I had this kind of features in mind for a while. Maybe with a slightly different implementation design.

* Adding $SOURCE variable sounds a good idea.
* Defining multiple sources in one block looks fine.

* I would advice stop putting additional example group data files in `/etc/clustershell`. File `groups` should never had been added there. `/etc/clustershell/groups.d/` or `/etc/clustershell/groups.conf.d/` looks better even if not perfect.

* In fact, my idea is slightly different. I was thinking of adding an internal parser for group source, using YAML. The idea is to avoid forking a lot of 'sed' when calling `nodeset -ll`  by example. This could be achieve subclassing GroupSource, using a filepath as a configuration variable, and loading the whole YAML file in the internal cache dict of GroupSource.
```
[foo]
path=/etc/clustershell/groups.d/config.yaml
```

**Comment by kcgthb** [comment]
> If you put everything in the same config file, that's a pain for management.

I beg to differ. :)
Gathering such thematic groups in the same file, on the contrary, eases management. When adding a new node to a cluster where multiple group sources are in use (such as rack position, hardware characteristics and so on), having to edit one file per type of group can rapidly get out of hands. Same if they're managed by Puppet.
But if those groupings are made as sections in the same file, everything is self-contained, easier to grasp as a whole, and less prone to errors ("Oops, I forgot to update that file...")

Besides, the proposed enhancement is exactly that: an enhancement. It allows more flexibility for the user, who could choose the better approach for her use-case (single file or not), as it still allows to keep the different sources in separate files. Best of both worlds.

**Comment by thiell** [comment]
Hm, as a reminder, dot-d directories are there for partial config files only, files in them are automatically combined. Hence the new directory named `groups.conf.d` we decided to add for 1.6. An application or puppet can then place its own group source config file there to integrate smoothly with ClusterShell. Like for `/etc/httpd/conf.d`. **We shouldn't use .d-named directories for any other purpose**, I guess...

But I agree these `/etc/clustershell/groups` or groups2 files are looking a little out of place. The best would be to put them in some `/etc/clustershell/userconf/` directory, but I also want that the sysadmin can easily edit this file, as it's sometimes a detailed reference of all cluster nodes. I'm not sure yet what to do for them.

Dot-d directories references:
http://blog.siphos.be/2013/05/the-linux-d-approach/
http://askubuntu.com/questions/7648/many-directories-have-a-d-suffix-extension-what-does-it-mean

As for the builtin YAML config file support idea, I am for it, but for a next release (1.8). Since PyYAML seems to be available in EL base now, I have no more objection of using it and adding this dependency, and yes we could thus get rid of those default sed upcalls!! Aurelien could you please open a separate ticket to track that feature?

**Comment by thiell** [comment]
https://review.gerrithub.io/239589

Due to upgrade constraint, I cannot change the default group source. So we're stuck with this local group source using `/etc/clustershell/groups` by default.

Current proposal is to add `/etc/clustershell/groups.conf.d/cluster.conf.example ` which uses `/etc/clustershell/groups.conf.d/cluster` (multi sources).

Also this patch enables `/etc/clustershell/groups.conf.d` in groups.conf IF user hasn't edited it yet (noreplace). This allows a better integration with other tools that install groups.conf files. We only put .example file there, so it shouldn't have a significant effect.

**Comment by degremont** [comment]
I'm still wondering where the best place to put configuration files used by group sources. If you have a lot of different configuration files, mixing everything in the same directory (``groups.conf.d``) makes it messy.

**Comment by thiell** [comment]
Despite my patch on gerrithub, I prefer to keep groups.conf.d for groups.conf "parts". Perhaps we should keep it simple and put random config in /etc/clustershell/ as soon as they don't conflict with default files. What is the problem of having /etc/clustershell/groups for example? The only I see if that now we cannot create a directory with this name. For our concerned file, what about /etc/clustershell/cluster.example?

**Comment by degremont** [comment]
The problem is people consider these files as official ClusterShell configuration files. ``groups`` intended to be an example of possibilities (originately using awk). They put more and more config files is the same directory for other sources. ``/etc/clustershell`` could be fill with too many files and I would like to limit this to really CS files (``clush.conf``, ``topology.conf``, ``defaults.conf``?).
 ``/etc/clustershell/groups/`` could have been a good place to put group sources data files BTW.

I'm pretty sure in the future we would see ``cluster.conf.d``. So let's be prepared for this right now.

**Comment by thiell** [comment]
Here is where I am:

* I agree that only main clustershell config files should reside in `/etc/clustershell/`
* I think also that `/etc/clustershell/groups/` would have been a very good place for sources data files, but it is not possible due to upgrade constraints, we have to choose another place. My new proposal is to put them in `/etc/clustershell/groupfiles/` by default (I prefer to avoid `groups.d` for that purpose).

BTW what are these upgrade constraints in details?
* users could have edited `/etc/clustershell/groups` (I do that myself, it's convenient), this file being installed as `%config(noreplace)`, we must continue to use it as the default group source (for upgrade at least)
* but users may also have edited `/etc/clustershell/groups.conf` (for example to add new sources or to enable `groups.conf.d` which was disabled by default...). As a `%config(noreplace)` file too, we have to support an old version of `groups.conf`...

As we can see there, these two config files are bound and that makes things worst.

One of our goal is to make `/etc/clustershell/groups` a deprecated config file. What can be done, especially for a fresh 1.7 install? Is it possible to remove it from 1.7? **I think I found a way to do it!** :)
The key seems to be the **%ghost** directive of %files section in specfile:

```
%ghost %{_sysconfdir}/clustershell/groups
```

 Tested use cases:
* Fresh 1.7 install: `/etc/clustershell/groups` is not installed, `groups.conf` pointing to new group source file (see below)
* Upgrade from 1.6: RPM will always keep `/etc/clustershell/groups` (modified or not, yes!), unless previously removed by user (of course). Yeah I just tested a bunch a possible use cases... The file is still registered as part of the clustershell package.

Still... a problem remains... with the following use-case:
* `groups.conf` not modified - and so legitimately upgraded by RPM as a `%config(noreplace)` file... which breaks a previous user config of `/etc/clustershell/groups` if we use a new file like `/etc/clustershell/groupfiles/default`.

The only solution I found for this case is that the new default source must check for `/etc/clustershell/groups` presence and use it first.

New 1.7 default group source proposal:
```ini
[local]
map: [ -f /etc/clustershell/groups ] && f=/etc/clustershell/groups || f=/etc/clustershell/groupfiles/default; sed -n 's/^$GROUP:\(.*\)/\1/p' $f
all: [ -f /etc/clustershell/groups ] && f=/etc/clustershell/groups || f=/etc/clustershell/groupfiles/default; sed -n 's/^all:\(.*\)/\1/p' $f
list: [ -f /etc/clustershell/groups ] && f=/etc/clustershell/groups || f=/etc/clustershell/groupfiles/default; sed -n 's/^\([0-9A-Za-z_-]*\):.*/\1/p' $f
```

Pro's:
* `/etc/clustershell/groups` is deprecated, and not even present in fresh install
* clean group sources flat files separation in `/etc/clustershell/groupfiles` that can be populated with `default` and `cluster` (multi-sources)
* upgrade from 1.6 doesn't break any config changes the user previously made

Con's:
* the new default group source is not sexy
* harder to package on Debian and other distros
