### ISSUE TITLE
Rename route section name in topology.conf to 'routes'

### ISSUE THREAD

**Issue by degremont** [cea-hpc/clustershell#259]
Currently, route definitions in `topology.conf` should be placed in `[Main]` section. This is not very meaningful. If we want to add other sections later, it could be easier if this name is change.

My proposal if to name it `[routes]` and still supports `[Main]` as compatibility layer. It should be easy to read both section if present and merge them. Documentation should tell to use `[routes]`

**Comment by thiell** [comment]
https://review.gerrithub.io/239600
