### ISSUE TITLE
Processing of '%' by NodeSet

### ISSUE THREAD

**Issue by brelr** [cea-hpc/clustershell#261]
Currently,
$> nodeset -e "a%b"
returns 'a%%b'
where we expect 'a%b'

Although,
$> nodeset -e "a%b[0]"
returns 'a%b0'

(the issue appears in clustershell-1.6-4.el7.noarch)

**Comment by thiell** [comment]
Hey, thank you Roger for reporting this. :-)

Not a common use-case I would say but still a bug.

Patch proposal: https://review.gerrithub.io/240553
