### ISSUE TITLE
nodeset: add a way to list groups from all group sources

### ISSUE THREAD

**Issue by thiell** [cea-hpc/clustershell#266]
With the increasing number of group sources, it would be convenient to have a easy way to list all groups from all group sources.

Today, it is only possible to list groups from the default group source:
```
$ nodeset -l
```
or just one selected group source using:
```
$ nodeset -l -s slurm
```

I propose to add `--list-all` or `-L` for that. With support of `-LL` and `-LLL` as for `-l` (will share the same function).

This new option should skip sources that don't provide the **list** upcall, without aborting (not like `-l`). However, in that case, a warning should be printed to stderr.

**Comment by degremont** [comment]
Why not provide a ``--allgroups`` or ``--allsources`` and keep ``-ll`` with its current behaviour. This avoids introducing a new ``-LL``

**Comment by thiell** [comment]
It's a new option in both cases... I think -L is more convenient for daily tasks. I understand the logic however. If really needed I can add --all-sources and make -L an alias of "-l --all-sources".

https://review.gerrithub.io/241398/
