### ISSUE TITLE
Add an option to prefix or suffix nodes

### ISSUE THREAD

**Issue by kcgthb** [cea-hpc/clustershell#277]
`-O` is great for expanding:
```
$ nodeset -O "prf-%s" -e a[0-1],b[3-4]
prf-a0 prf-a1 prf-b3 prf-b4
``` 
but not so much for folding:
```
$ nodeset -O "prf-%s" -f a[0-1],b[3-4]
prf-a[0-1],b[3-4]
```

What about having specific options to add a prefix (or a suffix) to node names? That can come particularly handy to manage multiple node interfaces (`node-eth0`, `node.ib0`, `ipmi-node`...) from regular hostname-based nodesets.

**Comment by thiell** [comment]
First thoughts...

As of today, I don't see a way to do it without expanding / editing each node / folding nodeset. That's utterly overkill. So to implement this feature the right way, unless I'm missing something, we need to add a mean to directly edit the underlying `NodeSet` object patterns. In your example, we have two patterns: `["a%s", "b%s"]`. We could add a public method to `NodeSet` to append/prepend/other? string to those patterns directly.

```python
nodeset.prefix("prf-") would lead to ["prf-a%s", "prf-b%s"]

nodeset.suffix("-ipmi") would lead to ["a%s-ipmi", "b%s-ipmi"]
```
or we could think of an more generic method:
```python
nodeset.format("prf-%s-ipmi")
```
I like that but the choice of format here could be confusing with str.format(), https://www.python.org/dev/peps/pep-3101/, as it wouldn't have any extra args. From a doc point of view, `%s` would represent each expanded node in the above methods, that is, 1D or nD.

Then, the nodeset CLI will just call this methods if a new option is provided. Or we could even change the behavior of -fO if we think that's a bug (that's not clear, the doc just says format **output**), but as you said, I don't see neither an useful use-case of -fO as of today.

**Comment by thiell** [comment]
And such a format feature could then also be easily added to clush (could help in scripts using clush sometimes), for example:

```console
$ clush -w login[1-2],node[1-9] --node-format "%s-ib0" -b echo ok
```

**Comment by degremont** [comment]
I think we can implement this simply updating the internal patterns:

```
for each pattern in nodeset:
   pattern = "prf-%s-ipmi" % pattern
```

We can wrap this in a simple method (just need to find a name to avoid conflicting with format)

I think we need to change the behaviour of -O. As you said -fO as no real sense right now.

**Comment by thiell** [comment]
Ok I guess we can implement this for 1.7.1 if we consider this as a bug. It shouldn't be to hard. We just need to find a good method name :)

**Comment by thiell** [comment]
I've just had a look at this issue it's a bit complicated to add a new public method to NodeSet for that, because when the format_string contains digits it will bypass the nD parsing code:

```python
    def apply_format(self, format_string):
        """Apply given format string to each nodeset pattern."""
        self._patterns = dict((format_string % pat, rset)
                              for (pat, rset) in self._patterns.iteritems())
```

```python
>>> from ClusterShell.NodeSet import NodeSet
>>> nodeset = NodeSet("node")
>>> nodeset.apply_format("%s-ipmi0")
>>> str(nodeset)
'node-ipmi0'
>>> nodeset.add("node-ipmi1")
>>> str(nodeset)
'node-ipmi1,node-ipmi0'
>>> nodeset._patterns
{'node-ipmi%s': 1, 'node-ipmi0': None}
```

Thoughts:
* add a private method to NodeSet only used by CLI/Nodeset.py (still I don't like much to have digits in patterns even if it's only a one-shot change...)
* check for digit in format_string and raise an error if found, but that could be annoying for pattern like %s-ib0, so the feature could be useful...
* implement a robust apply_format() public method that would correctly apply new format to patterns and recompute nD stuffs (but that's a lot of work I guess and I'm not sure to have a way to make it more optimized that expanding / editing each node / folding nodeset).

So I guess my preferred way right now is:
* `nodeset -fO` leads to expanding / formatting each node and creating a new nodeset with them (no NodeSet.py changes needed)

**Comment by degremont** [comment]
Ok for changing only CLI . This feature is only for very lazy guys anyway as it is very simple to implement it in Python or Bash wrapping ClusterShell...

**Comment by kcgthb** [comment]
> it is very simple to implement it in Python or Bash wrapping ClusterShell.

Well, the only way I see of doing this would be to call nodeset once to expand the list, then modify the nodenames, and call nodeset again to re-factor it. Like this:

```
$ nodeset -f $(nodeset -e a[0-1],b[3-4] | sed 's/^/ipmi-/;s/ \</ ipmi-/g')
ipmi-a[0-1],ipmi-b[3-4]
```

Even the regexp is ugly...

If you have a better solution, I'd be happy to see it. :)

**Comment by degremont** [comment]
Actually, this is already implemented :)

```
$ nodeset --contiguous -O "prf-%s" -f a[0-1],b[3-4]
prf-a[0-1]
prf-b[3-4]
```

**Comment by kcgthb** [comment]
Nice try, but no: I want the output to be *one* nodeset, not multiple lines. 
```
$ nodeset --contiguous -O "prf-%s" -f a[0-1],b[3-4,8-10]
prf-a[0-1]
prf-b[3-4]
prf-b[8-10]
```
Ugh! 
With this, I would still need to run `nodeset -f` over the results. It's as bad as `cat | grep` :)
