### ISSUE TITLE
Nodesets cannot start with a number

### ISSUE THREAD

**Issue by hdoreau** [cea-hpc/clustershell#284]
We have nodesets like "0123[0-100]L6" and would like to use ClusterShell.NodeSet to manage them. Unfortunately, it seems that such a format was explicitly forbidden. What was the reason behind? Would you accept (or write :) a patch that drops that limitation?

**Comment by kcgthb** [comment]
Coucou Henri, 

RFC 952 mandates that hostnames could not start with a digit. That's probably why.

**Comment by thiell** [comment]
RFC 1123 relaxes the constraint: _"The syntax of a legal Internet host name was specified in RFC-952 [DNS:4].  One aspect of host name syntax is hereby changed: the restriction on the first character is relaxed to allow either a letter or a digit.  Host software MUST support this more liberal syntax."_

Good answer here I guess - says that only the TLD cannot start with a digit to avoid confusion with IPv4: http://serverfault.com/questions/638260/is-it-valid-for-a-hostname-to-start-with-a-digit

Darn, we're too RFC 952!

**Comment by kcgthb** [comment]
Pfff, those reformed and lax RFCs are the reason why we have systemd, now...

**Comment by hdoreau** [comment]
Hi there, thanks for your answers.

It's good that RFC 1123 supports this horror of having digit-prefixed hostnames, it backs my request. But my question could be: are nodesets intended to designate hosts only or generic matrix nodes?

I would find the latter extremely handy. A way to easily subclass NodeSet would ease the implementation of a workaround. What do you think?

**Comment by degremont** [comment]
Unfortunately (or maybe this is rather a good thing), people uses NodeSet for almost anything that uses a ID and could be folded. This is a sign of CS success.
If there is no technical reason that prevents it, I would rather advise to support this syntax, as long as there is at least one non-digit character (else that a RangeSet).
Looking quickly at the code I saw no reason to prevent it.
NodeSet will soon be an alias for AnythingSet :)

**Comment by thiell** [comment]
NodeSet aims to support all possible cluster hostnames, so we should fix that in 1.7.1. By supporting all possible hostnames, it allows a wide range of other use cases as well, as long as they conform to RFC 1123.

**Comment by thiell** [comment]
Oh and btw, `0123[0-100]L6` might give you weird result due to padding, only `0123[000-100]L6` will really be supported, is that OK? (see _padding mismatch_ case in #228)

**Comment by thiell** [comment]
Ok I had a look and hopefully looks like it's just an easy-to-fix small defect. Will do more testing before patch submission and review though.

Your example `0123[0-100]L6` will result in `[01230-123100]L6`. Be careful, it's weird, as the length of the range changes when "amending" leading digits (e4c2c468b809866824d362db3d3ab2302e350fb6), but it's supported:
```console
$ ./nodeset.py -c 0123[0-100]L6
121871
```

`0123[000-100]L6` will result in `[0123000-0123100]L6` (same range length, more that what we can usually expect) 

```console
$ ./nodeset.py -c 0123[000-100]L6
101
```

**Comment by thiell** [comment]
https://review.gerrithub.io/262652
