### ISSUE TITLE
Nodeset removes zeroes(0) from node names

### ISSUE THREAD

**Issue by alexbozhenko** [cea-hpc/clustershell#286]
Hello. I noticed that zeroes(0) removed from node names on this set:

```
$ echo "n1c01,n1c02,n1c03,n1c04,n1c05,n1c06,n1c07,n1c08,n1c09,n2c01,n2c02,n2c03,n2c04,n2c05,n2c06,n2c07,n2c08,n2c09,n3c01,n3c02,n3c03,n3c04,n3c05,n3c06,n3c07,n3c08,n3c09,n4c01,n4c02,n4c03,n4c04,n4c05,n4c06,n4c07,n4c08,n4c09" | nodeset -f

n[1-4]c[1-9]

```
And not everything is good on this set, where I just deleted 2 last nodes:

```
$ echo "n1c01,n1c02,n1c03,n1c04,n1c05,n1c06,n1c07,n1c08,n1c09,n2c01,n2c02,n2c03,n2c04,n2c05,n2c06,n2c07,n2c08,n2c09,n3c01,n3c02,n3c03,n3c04,n3c05,n3c06,n3c07,n3c08,n3c09,n4c01,n4c02,n4c03,n4c04,n4c05,n4c06,n4c07" | nodeset -f

n[1-3]c[01-09],n4c[01-07]
```

Compare n[1-4]c**[1-9]** vs n[1-3]c**[01-09]**,n4c[01-07]

**Comment by thiell** [comment]
Hi @alexbozhenko,

Ugh. Thanks much for reporting! Your first example looks like a 0-padding bug. If you remove ",n4c08,n4c09" at the end, it works as expected! I will take a look at it ASAP.

What is the error in your second example? for me in your nodeset you have `n[1-3]c[01-09]` plus `n4c[01-07]`.

**Comment by thiell** [comment]
This strange behavior is due to a heuristic-folding we developed to speed up thing in some cases. When adding one more node to your last example, you triggered a different nodeset folding code where 0-padding info was badly handled. Thanks again for reporting this issue, this is very helpful.

Patch in review - https://review.gerrithub.io/262943

**Comment by alexbozhenko** [comment]
Hello, Thiell.

Thank you for instant fix and coolest ssh cluster software.
I confirm, that with your fix both nodeset and clush now works. 

But I also noticed that clubak affected as well:

```
[alex@localhost tmp]$ clush -w  n1c01,n1c02,n1c03,n1c04,n1c05,n1c06,n1c07,n1c08,n1c09,n2c01,n2c02,n2c03,n2c04,n2c05,n2c06,n2c07,n2c08,n2c09,n3c01,n3c02,n3c03,n3c04,n3c05,n3c06,n3c07,n3c08,n3c09,n4c01,n4c02,n4c03,n4c04,n4c05,n4c06,n4c07,n4c08,n4c09 -l alex uptime  | clubak
Traceback (most recent call last):
  File "/usr/bin/clubak", line 10, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/ClusterShell/CLI/Clubak.py", line 182, in main
    clubak()
  File "/usr/lib/python2.7/site-packages/ClusterShell/CLI/Clubak.py", line 175, in clubak
    options.trace_mode, enable_nodeset_key is not False)
  File "/usr/lib/python2.7/site-packages/ClusterShell/CLI/Clubak.py", line 96, in display
    disp.print_gather(node, tree[str(node)])
  File "/usr/lib/python2.7/site-packages/ClusterShell/MsgTree.py", line 215, in __getitem__
    return self._keys[key]
KeyError: 'n2c1'
```

(To test I just added to my /etc/hosts:
```
127.0.0.1 n1c01
127.0.0.1 n1c02
127.0.0.1 n1c03
127.0.0.1 n1c04
127.0.0.1 n1c05
127.0.0.1 n1c06
127.0.0.1 n1c07
127.0.0.1 n1c08
127.0.0.1 n1c09
127.0.0.1 n2c01
127.0.0.1 n2c02
127.0.0.1 n2c03
127.0.0.1 n2c04
127.0.0.1 n2c05
127.0.0.1 n2c06
127.0.0.1 n2c07
127.0.0.1 n2c08
127.0.0.1 n2c09
127.0.0.1 n3c01
127.0.0.1 n3c02
127.0.0.1 n3c03
127.0.0.1 n3c04
127.0.0.1 n3c05
127.0.0.1 n3c06
127.0.0.1 n3c07
127.0.0.1 n3c08
127.0.0.1 n3c09
127.0.0.1 n4c01
127.0.0.1 n4c02
127.0.0.1 n4c03
127.0.0.1 n4c04
127.0.0.1 n4c05
127.0.0.1 n4c06
127.0.0.1 n4c07
127.0.0.1 n4c08
127.0.0.1 n4c09
```
And increased MaxSessions in /etc/ssh/sshd_config.

**Comment by thiell** [comment]
Thanks @alexbozhenko for the feedback, much appreciated!

I will take a look at clubak too. Please note that most of clubak features are available directly through clush. For example, in that case, you can use `clush -b` and avoid the use of `clubak` at all.

**Comment by degremont** [comment]
@alexbozhenko FYI, the proposed patch was updated, taking into account your latest comment. All reported issues should be fixed with this version.
