### ISSUE TITLE
clush: stdin behavior expectations with non-writable workers

### ISSUE THREAD

**Issue by thiell** [cea-hpc/clustershell#287]
While performing some tests, I noticed the following (unhandled) error in 1.7 with the pdsh worker (**not** writable):
```console
$ echo | clush -w localhost --worker ssh true
$ echo | clush -w localhost --worker pdsh true
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/ClusterShell/CLI/Clush.py", line 745, in clush_excepthook
    raise exp
ClusterShell.Worker.EngineClient.EngineClientNotSupportedError: writing is not supported by pdsh worker
```

At the moment (1.7), clush enables stdin reading by default whenever possible but doesn't check whether the worker is writable.

To summarize the current behavior:

1. first, if `--nostdin` option is provided, clush doesn't perform any stdin-related handling...

2. when stdin is a tty and stdout is also a tty with "foreground presence", clush starts what we call the "user interaction" mode (you can check the debug message at launch: "User interaction: true/false") - in that case another thread is used for the task, the main thread calling `ttyloop()`, basically to watch for user input (`raw_input()`)

3. else if stdin is not a tty, clush calls `bind_stdin()`  that creates a blocking thread reading stdin - any input read here is sent to the task in a thread-safe manner (via a task [port](http://pythonhosted.org/ClusterShell/ClusterShell.Worker.EngineClient.EnginePort-class.html)) and handled by the port handler `StdInputHandler` that calls a `worker.write()` when some data is coming or calls `worker.set_write_eof()` when EOF is encountered.

Note, just to confirm 1:

```console
$ echo | clush -w localhost --worker ssh --nostdin true
$ echo | clush -w localhost --worker pdsh --nostdin true
$ 
```

I would like to discuss a fix for **3**.

First thing is obviously to properly handle the exception (`ClusterShell.Worker.EngineClient.EngineClientError` and subclasses like `EngineClientNotSupportedError`), this is missing.

I fixed that, but still a problem remains:

```console
$ echo foo | while read a; do ./clush.py -w localhost --worker ssh true; done
$ echo foo | while read a; do ./clush.py -w localhost --worker pdsh true; done
clush.py: EngineClientError: writing is not supported by pdsh worker
```

Indeed in that case, clush always initializes a stdin reader thread, but we won't notice, unless `set_write_eof()` isn't supported by the worker.

versus:

```console
$ echo foo | while read a; do ./clush.py -w localhost --worker ssh --nostdin true; done
$ echo foo | while read a; do ./clush.py -w localhost --worker pdsh --nostdin true; done
$ 
```

I first thought that I should deactivate the stdin reader thread (ie. `--nostdin`) for workers that don't support it, but then commands like the following won't even return an error and will block indefinitely:
```console
$ echo -n | ./clush.py -w localhost --worker pdsh cat   (imagine here an implicit --nostdin)
<blocked>
```

All of that to say that I'll probably just fix the exception handler, or I could implement something like:
```
if worker is non-writable:
    if clush detects any output on stdin:
        abort with  "writing is not supported by worker"
    but if clush detects an EOF on stdin:
       do NOT call set_write_eof() at the other end
```

clush would act as a wrapper that cannot fix every cases (like cat) but at least would allow the above `while read` script to work with `--worker pdsh`.

I know... this is probably not something really important, but in case you have a better idea, please let me know!

**Comment by degremont** [comment]
After getting a headache trying to understand every aspect of this :), I do not have a magical idea which handle everything. I'm not sure doing some magic here is really a good idea. I would go only for the exception catch.

If you do this patch, this will work fine:
```
echo foo | while read a; do ./clush.py -w localhost --worker pdsh true; done
```

But when you are doing such loop, you are expecting more than one read
```
echo -e "line1\nline2\n" | while read a; do ./clush.py -w localhost --worker pdsh true; done
```

And this won't work I think as clush will still try to read from stdin, so will raise a traceback.

So there is only one case where this is will work fine and I do not think it is interesting.
