### ISSUE TITLE
WorkerPopen.current_node is no more None

### ISSUE THREAD

**Issue by degremont** [cea-hpc/clustershell#289]
Since version 1.7, current_node for WorkerPopen instances is no more None, as it used to be until then. 
Library users, as MilkCheck, relies on this value to make the difference between a local and a distant worker by example.

**Comment by degremont** [comment]
https://review.gerrithub.io/264066

**Comment by thiell** [comment]
Thanks! As discussed on gerrit, I'm going to land this patch to restore old behavior and we should think of long-term fix/API improvement for 1.8 (this can be tracked by #103). But for sure, we'll have to keep `current_node` value as `None` for compatibility.
