### ISSUE TITLE
WorkerTree does not support --rcopy

### ISSUE THREAD

**Issue by degremont** [cea-hpc/clustershell#290]
It looks like reverse copy mode in not supported with current tree mode.

Leading in strange error reporting that the (remote) file does not exist (actually, when ```tarfile.add()``` is trying to read it, locally)
When using ```--rcopy```, it is just tring to do a ```--copy```

**Comment by thiell** [comment]
Darn. Forgot about that!

I would like to land 1.7.1 as soon as possible and work on this one for 1.7.2, do you agree with that?

**Comment by thiell** [comment]
https://review.gerrithub.io/#/c/264560

Works like a charm, but not tested at scale... :)
