### ISSUE TITLE
nodeset dropping leading zeros from hostnames with larger node lists

### ISSUE THREAD

**Issue by tonykew** [cea-hpc/clustershell#292]
nodeset has a problem with larger host lists, dropping leading zeros from the hostname

Test case example in the attached zip file:
[nodeset_testcase.zip](https://github.com/cea-hpc/clustershell/files/153193/nodeset_testcase.zip)

The problem is not seen with version 1.6
Problem appeared with version 1.7
Sill present with NodeSet.py from git

**Comment by thiell** [comment]
Hi @tonykew - thank you for the nice reproducer. This issue was introduced in 1.7 and located in `RangeSet.py` (and not `NodeSet.py` ;-)) and is indeed fixed in 1.7.1 or git.
