### ISSUE TITLE
NodeSet: consider empty string as valid nodeset

### ISSUE THREAD

**Issue by thiell** [cea-hpc/clustershell#294]
`nodeset` may return an empty string as a result of a set operation. So for scripts reusing `nodeset` output we should consider allowing the empty string '' as a valid empty nodeset instead of raising `NodeSetParseError`.

At the library level, None is currently a valid argument for an "empty" NodeSet object. We should probably allow the empty string "" too.

**Comment by kcgthb** [comment]
Use case:
```
$ nodeset -c foo -x foo
0
```
But:
```
$ nodeset -c "$(nodeset -e foo -x foo)"
nodeset: Parse error: empty node name
```

**Comment by degremont** [comment]
Strictly speaking this is a change in library behaviour but I see no problem to change it anyway.

I'm OK with a patch authorising ``ns = NodeSet("") `` as an empty nodeset.

**Comment by kcgthb** [comment]
Oh and there seem also to be a different path to get to this, when using operators such as exclusion:

``` 
$ nodeset -e a[0-3] -x a2
a0 a1 a3
$ nodeset -e a[0-3] -x ""
nodeset: Parse error: empty node name
```
