### ISSUE TITLE
rcopy does not work in tree mode (with topology file)

### ISSUE THREAD

**Issue by sm-bull** [cea-hpc/clustershell#296]
Hi!

I'm currently using clush in our solution, and I found this bug when using the rcopy function. If a topology file is set, the rcopy does not work anymore. I have tested to remove the topology file and it works.

The operations to reproduce the bug:

topology file:
[Main]
adm: bashful,grumpy
bashful: node1[01-02,10-13]
grumpy: node103

commands:

```
user@adm $ clush --topology /path/to/topofile -w node10[1,2] -c /path/to/file.test --dest /tmp
user@adm $ clush --topology /path/to/topofile -w node10[1,2] --rcopy /tmp/file.test --dest /tmp
clush: [Errno 2] No such file or directory: '/tmp/file.test'
```

It looks like it searches the file locally instead of remotely.

**Comment by thiell** [comment]
Hi @sm-bull,
What version of clustershell are you using? This should have been fixed in #290 and available in 1.7.1.

**Comment by sm-bull** [comment]
Ok, it is fixed. We used the version 1.7.

Sorry for this issue.

**Comment by thiell** [comment]
No worries. 1.7.1 is still in epel-testing for now and should be available in epel in a few days. The same package is available for download here on github.
