### ISSUE TITLE
Add option to pick random nodes in nodeset for nodeset/clush commands

### ISSUE THREAD

**Issue by martinetd** [cea-hpc/clustershell#311]
I'd like to add an option to nodeset and clush commands to pick one or n random elements of the given nodeset.
For example, single node usage could be used as a quick load balancer between workers.

Quick implementation: https://review.gerrithub.io/#/c/279372/

Up to discussion:
- option names (--pick, --random, --sample, other? which takes argument?)
- having a syntax in nodeset like foo[1-10?SAMPLE] a bit like autostep? (if so, could factor the ugly random.sample+intersection code in NodeSet)
- rather than intesect, building a new nodeset?
- doesn't seem to work with the rangeset option for nodeset
- import random or from random import sample ?
- will add tests when we're happy with option names/general feeling

**Comment by degremont** [comment]
By the way,  I prefer ``--pick=4`` and ``--pick`` as it really means that it will take fewer nodes than the whole nodeset. ``--shuffle`` makes me think ``clush`` will starts command execution, using fanout, out of order, which is not the case (and is a required improvements). So keep this name for something else.

**Comment by degremont** [comment]
> * option names (--pick, --random, --sample, other? which takes argument?)
Yes, with arguments
Use ``pick`` (or sample)

> import random or from random import sample ?

If you makes few call to random objects, just use ``import random``. If you are using ``random.something`` in a lot of places in the code, use ``from random import something``

**Comment by thiell** [comment]
We also need to update the doc. I can do it in another commit. Some simple scripts to update the man pages from rst files are not in the repo.
