### ISSUE TITLE
Display tree only in debug mode

### ISSUE THREAD

**Issue by degremont** [cea-hpc/clustershell#315]
When using ``clush`` in verbose mode (especially useful while copying by example), displaying the topology graph for each command is annoying. In my configuration, graph output needs more than 20 lines, this is spamming my terminal. 
I do not think people really needs it every time there are running a command in verbose. I would recommend to show it in debug mode only.

**Comment by thiell** [comment]
I will try to evaluate the effort first but that should be doable :p
