### ISSUE TITLE
nodeset: display warning on no-op (due to option order)

### ISSUE THREAD

**Issue by thiell** [cea-hpc/clustershell#318]
nodeset arguments have always been tough to manage, we even changed the behavior between 1.1 and 1.2. Since v1.2, the order of options matters. However, the current behavior could lead to errors in some cases. Take for example the following case:

``` console
$ nodeset -f -i foo1 foo[1-2]
foo[1-2]
```

No warning/error is issued. I would like to add a warning in that case, so that the user knows `-i foo1` placed here is useless.

The correct syntax if you want to compute nodeset intersection is:

``` console
$ nodeset -f foo[1-2] -i foo1
foo1
```

Or we could roll back to 1.1's behavior. I did some test with argparse (#316) and that would mean a much simpler code, but I assume that is too much of a change...

**Comment by degremont** [comment]
We should definitely not rollback to 1.1 behaviour. Polish notation is not admin friendly at all.

We could add a warning message if you want.
