### ISSUE TITLE
When login as root "Permission denied  (publickey, password)"

### ISSUE THREAD

**Issue by d0pa** [cea-hpc/clustershell#328]
There no issues so far when public key is added for a user. When on a new node public key is added for a root user, in interactive clush I cannot execute any commands because "Permission denied  (publickey, password)". While ssh root@node works fine and command  "echo 'pass' | clush -w node sudo -S  command" also works. 

How should root user be setup to allow root privileges ?

**Comment by thiell** [comment]
@d0pa: hmm, if you are logged in as a non-root user and have a working public key for root, you just need to do the following:

```
clush --user root -w node ...
```

**Comment by d0pa** [comment]
It works ! Thank you very much !
