### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by grafoo** [cea-hpc/clustershell#337]
hi!
will python3 be supported in any foreseeable future?

cheers, manuel

**Comment by thiell** [comment]
Hi @grafoo. AFAIK, ClusterShell is mainly used in the HPC world where Python 3 is not available at the default system Python interpreter. The HPC software stack takes time to evolve and thus we also had to ensure compatibility with old Python versions, like Python 2.4 on CentOS 5 and 2.6 on CentOS 6.

But right now, we have a few open tickets related to Python 3 support, as for example:
- #239 is handling the support drop of Python 2.5 and below (first patches landed)
- #316 is handling the migration to argparse

Can you please describe more in detail your use-case of ClusterShell and why Python 3 would be useful in your case? Thanks!

**Comment by grafoo** [comment]
sorry for the delay.
there is no particular use-case for python3.
i'm in the middle of evaluating different frameworks and python3-support was just one item on the pro/con-list.
thanks for the fast response and keep up the good work!
cheers, m

**Comment by degremont** [comment]
For your information we are very closed to have master branch supporting Python 3 for "nodeset" like features. Support for clush & co will probably be more difficult and will require more time.

**Comment by degremont** [comment]
I'm reopening this ticket to follow Python 3 support effort. There is a couple of patch in the pipe for that.

**Comment by volans-** [comment]
@thiell It's very nice to see some effort in this direction, I'm looking forward to the Python 3 support too.

The main reason being that I've developed a tool (usable both via CLI and as a Python library) that uses ClusterShell as a library and now I'm starting to develop additional softwares that uses this tool as a library.
ClusterShell is the only dependency non-Python 3 ready and this means that the tool itself had to be written in Python 2 and as a consequence also any software that uses it as a library. This will generate quite a bit of technical debt and being able to start already in Python 3 would really help.

I'm also available to help, so if you have any specific subtasks for the Python 3 support feel free to loop me in and I'll see what I can do.

**Comment by thiell** [comment]
@volans- thanks for your feedback, much appreciated! As you have probably noticed, things are moving forward.  If you want to contribute, feel free to submit a PR at any time, and as for code review, we still work on gerrithub so feel free to review any patch there. Also, we will welcome Python 3 testers as soon as this work is completed.

**Comment by volans-** [comment]
@thiell Thanks, will do!
Although I'll have to do it from a different account, my GitHub name is not a valid Gerrit name so I can't login on GerritHub with this one 😞

**Comment by rppendya** [comment]
@thiell, My team is working on a tool that was initially written in python 2 and now we want to move our tool to support Python 3. When we evaluated our dependencies, we realized clustershell doesn't yet support Python 3. We are specifically using Nodeset and Rangeset in clustershell. Do you have any estimated date on when clustershell 1.8 will be released? My team already noticed Nodeset and Rangeset in Master can support Python 3. If it's going to take too long, can you guys consider doing a beta release of current master so that it will be easy for our tool to be packaged in Python 3. 
Thanks for your help and providing us this awesome tool!!

**Comment by thiell** [comment]
@rppendya Hey thanks for your interest in clustershell. Indeed Python 3 support is now complete. We plan to release a beta version of 1.8 next week or so. Just curious, is your project available online somewhere? I'm always curious to see how CS is used in practice.

**Comment by rppendya** [comment]
@thiell Thanks for the update. https://github.com/intel-ctrlsys/actsys is our project

**Comment by rppendya** [comment]
Thanks @thiell
