### ISSUE TITLE
Hardwired options are not overridable on commandline.

### ISSUE THREAD

**Issue by alexbozhenko** [cea-hpc/clustershell#340]
In this commit
https://github.com/cea-hpc/clustershell/blob/6e4e131f454b2ac37cfcd93e1a17d9a39bbbe951/lib/ClusterShell/Worker/Ssh.py#L60
there is a comment
> Add custom ssh options first as the first obtained value is used. Thus all options are overidable by custom options. 

Looks like it is not the case:
```
[alex@host ClusterShell]$ ssh -A -a  remotehost 'env | grep SSH_AUTH_SOCK; echo $?' 
1
[alex@host ClusterShell]$ ssh -a -A  remotehost 'env | grep SSH_AUTH_SOCK; echo $?' 
SSH_AUTH_SOCK=/tmp/ssh-LsWLOAXZGe/agent.10338
0
```
When we specify `-a`(not forward agent), and then `-A`(forward agent) it is forwarded.
You can also play with order of `-q` and `-v` to confirm. Last specified option wins, because they iterate over options in a while loop https://github.com/openssh/openssh-portable/blob/V_7_5_P1/ssh.c#L608

Hence this doesn't work as expected:
```
clush -d -o "-A" -w  remotehost 'env | grep SSH_AUTH_SOCK; echo $?'
DEBUG:root:clush: STARTING DEBUG
clush: nodeset=remotehost fanout=64 [timeout conn=15.0 cmd=0.0] command="env | grep SSH_AUTH_SOCK; echo $?"
SSHCLIENT: 
ssh -A -a -x -oConnectTimeout=15 -oBatchMode=yes remotehost env | grep SSH_AUTH_SOCK; echo $?
...
1
```

I think this statement about order came from here:

```
SSH_CONFIG(5)                                                          BSD File Formats Manual                                                         SSH_CONFIG(5)

NAME
     ssh_config — OpenSSH SSH client configuration files

SYNOPSIS
     ~/.ssh/config
     /etc/ssh/ssh_config

DESCRIPTION
     ssh(1) obtains configuration data from the following sources in the following order:

           1.   command-line options
           2.   user's configuration file (~/.ssh/config)
           3.   system-wide configuration file (/etc/ssh/ssh_config)

     For each parameter, the first obtained value will be used. 
```

Looks like that means that value in 1. will override value in 2, and value in  2. overrides 3.
That also true for order of options in the config file.
E.g, this result to forwarding enabled:
```
Host *
  ForwardAgent yes
  ForwardAgent no
```
This result to forwarding disabled:
```
Host *
  ForwardAgent no
  ForwardAgent yes
```

But since it is not the case for cli, I think adding custom options should be done in the very end, to let user effectively override everything hardwired, unless you think it should be fixed in openssh-client.

I used these versions:
```
[root@scrmca01arbco001 alex]# rpm -qa  | grep -e openssh-c -e clustershell
openssh-clients-6.6.1p1-31.el7.x86_64
clustershell-1.7.2-1.el7.noarch
```

**Comment by thiell** [comment]
@alexbozhenko thanks for this detailed bug report!

I played a bit with -x/-X in the same way you did with -a/-A and I do confirm that the LAST parameter on command line takes precedence.

I used the following version of openssh:

OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8, OpenSSL 1.0.1f 6 Jan 2014
OpenSSH_7.1p2, OpenSSL 1.0.1e-fips 11 Feb 2013
OpenSSH_7.3p1c-GSI NMOD_3.19-hpn14v12 GSI, OpenSSL 1.0.1e-fips 11 Feb 2013

We'll have to fix that in clustershell. I have a few things to work on first so feel free to submit a PR in the meantime.

**Comment by alexbozhenko** [comment]
Hi, @thiell.

I also found that specifying options in long format does work as described(first obtained value is used):
```
ssh -oConnectTimeout=15 -oBatchMode=yes -oForwardAgent=no -oForwardAgent=yes  remothost 'env | grep SSH_AUTH_SOCK; echo $?'
1
```
```
ssh -oConnectTimeout=15 -oBatchMode=yes -oForwardAgent=yes -oForwardAgent=no  remothost'env | grep SSH_AUTH_SOCK; echo $?'
SSH_AUTH_SOCK=/tmp/ssh-jYxUcR4805/agent.4805
0
``` 
Also, specifying option in short format wins wherever is it placed: 
```
ssh -q -A  -oConnectTimeout=15 -oBatchMode=yes -oForwardAgent=no -oForwardAgent=yes  remotehost 'env | grep SSH_AUTH_SOCK; echo $?'
SSH_AUTH_SOCK=/tmp/ssh-KCCjFu5440/agent.5440
0
ssh -q -a  -oConnectTimeout=15 -oBatchMode=yes -oForwardAgent=no -oForwardAgent=yes  remotehost 'env | grep SSH_AUTH_SOCK; echo $?'
1
ssh -q  -oConnectTimeout=15 -oBatchMode=yes -oForwardAgent=yes -oForwardAgent=no -A  remotehost 'env | grep SSH_AUTH_SOCK; echo $?'
SSH_AUTH_SOCK=/tmp/ssh-QxvIVW5488/agent.5488
0
ssh -q  -oConnectTimeout=15 -oBatchMode=yes -oForwardAgent=yes -oForwardAgent=no -a  remotehost 'env | grep SSH_AUTH_SOCK; echo $?'
1
```

So may be just not using short format for hardwired options is the solution for ssh. That way users options, either in short or long format, will come first and override hardwired ones.
So change
`cmd_l += [  "-a", "-x"  ]`
to
`cmd_l += [  "-oForwardAgent=no", "-oForwardX11=no"  ]`
I will prepare PR for this.

But also nor sure about scp options:
https://github.com/cea-hpc/clustershell/blob/master/lib/ClusterShell/Worker/Ssh.py#L108
Those `-r` and `-p` are not overridable anyways. I do not see negative options in `man scp`, so that comment just should be removed?

**Comment by thiell** [comment]
@alexbozhenko thanks for taking the time to look into this

re: scp options, yes that comment should be removed, we need to think of something better for the long term but that can be done later. 

The priority is to fix the bug and your last change proposal sounds good to me.
