### ISSUE TITLE
Nested group + Node resolution

### ISSUE THREAD

**Issue by SyntaxRules** [cea-hpc/clustershell#342]
I've created a custom group resolver and set it as the std_group_resolver. Here are my example groups:

I've run into a exception when using nested lists. When I set my lists to:
```
test: @test1,c1
test1: c99
```
And run:
```
list(NodeSet("@test")
# works fine prints:
# c[1,99]
```

But when I set my lists to:
```
test: @test1,c[1-2]
test1: c99
```
And run:
```
list(NodeSet("@test")
# Traceback (most recent call last):
#    File "/usr/lib64/python2.7/site-packages/ClusterShell/NodeSet.py", line 310, in __str__
#    raise NodeSetParseError(pat, "Internal error: node pattern and "
# ClusterShell.NodeSet.NodeSetParseError: Internal error: node pattern and ranges mismatch: "c%s"
```

From the exception message, it appears that NodeSet was not expecting c[%s], like I passed it, but rather c%s. 

I've seen some documentation/examples where group lists work like `@group1,@group2`. but I haven't seen any with `@group1,node[1-10]`. I this a feature that intended to work with NodeSets, or have I pushed it beyond what it was intended?

**Comment by thiell** [comment]
Hi @SyntaxRules - I cannot reproduce this issue using the default group resolver (`default = local` in group.conf) nor the YAML group resolver (eg. `default = roles` in groups.conf). I do confirm that the `@group1,node[1-10]` syntax is/should be fully supported. Would you be willing to share your group resolver to help troubleshoot this issue? Thanks!

**Comment by SyntaxRules** [comment]
This seems to be specific to my instance.

**Comment by MarbolanGos** [comment]
Quite a long time after I would like to re-open this as I reproduced in RHEL8.9:
```
# time clush -f 480 -bw jpbo-[001-040]-[01-48] --remote=no 'ping -t 5 -c 1 -q %h-bmc &>/dev/null' 
clush:    0/1920 gw 2
clush: interrupt (^C to abort task)
clush: in progress(2): gateway-ssh-service.region[1-2].svc.kube.local
clush: [tree] open gateways(2): gateway-ssh-service.region[1-2].svc.kube.local
clush: [tree] in progress(960) on gateway-ssh-service.region1.svc.kube.local: jpbo-[001-020]-[01-48]
clush: Parse error: Internal error: node pattern and ranges mismatch: "jpbo-%s-%s"

real    0m1.926s
user    0m0.564s
sys     0m0.027s
```
