### ISSUE TITLE
Performance regression for NodeSet.remove() since 95b3c43

### ISSUE THREAD

**Issue by degremont** [cea-hpc/clustershell#346]
Since commit 95b3c43 "remove _wrap_set_op() for Python 3 support" was landed, there is a big performance regression for NodeSet.remove() when element is NOT present in NodeSet.

```
 NodeSetRemove         before=0.57536   after=2.97124     +416%
```
This test is using 1-dimension NodeSet pattern.

I tracked this down to this part of code of `RangeSet.py:RangeSet.difference_update()`
```python
        if strict and other not in self:
            raise KeyError(other.difference(self)[0])
```

Computing `other.difference(self)` is very expensive.

But for some reasons I cannot show this performance impact in a simpler test case, like using only RangeSet.

**Comment by thiell** [comment]
Code is at https://github.com/cea-hpc/clustershell/blob/master/lib/ClusterShell/RangeSet.py#L685

**Comment by thiell** [comment]
I wasn't able to reproduce using your perf bench suite so far. When you say "when element is NOT present in NodeSet", do you mean something like:

```py
class NodeSetRemove(BenchTest):

    def setup(self):
        self.ns = random_ns(NB_ELEM)
        self.empty = NodeSet()

    def run(self):
        for i in range(1000):
            self.ns.remove(self.empty)
```
?

Please attach a reproducer so I can take a look.

**Comment by degremont** [comment]
You need to do it against a non-empty NodeSet.

```python
class NodeSetRemoveMissing(BenchTest):

    def setup(self):
        self.ns = random_ns(NB_ELEM)
        self.nodes = random_nodes(NB_ELEM)

    def run(self):
        for item in self.nodes:
            try:
                self.ns.remove(item)
            except KeyError:
                pass
```

**Comment by thiell** [comment]
Ok now I can see a performance regression indeed, I'll check.

```
 TESTNAME                 v1.7.3    d0ea10c    95b3c43     master
 NodeSetRemoveMissing    0.04748    0.04863    0.07238    0.07197
```

**Comment by thiell** [comment]
I can see 2 issues in that case: a costly recursion (CPython is very bad at it) and also the cost of self.copy() in `difference()` after 95b3c43.

The recursion is visible by profiling (see 16039/9999).

```
d0ea10c:
$ python -m cProfile nsremove.py  | grep difference_update
     9999    0.016    0.000    0.654    0.000 NodeSet.py:1471(difference_update)
     9999    0.020    0.000    0.115    0.000 NodeSet.py:635(difference_update)
     9999    0.021    0.000    0.089    0.000 RangeSet.py:695(difference_update)


95b3c43:
$ python -m cProfile nsremove.py  | grep difference_update
     9999    0.017    0.000    1.281    0.000 NodeSet.py:1471(difference_update)
     9999    0.021    0.000    0.758    0.000 NodeSet.py:635(difference_update)
16039/9999    0.617    0.000    0.731    0.000 RangeSet.py:679(difference_update)
```

nsremove.py being close to your test case:

```py
    ns = random_ns(NB_ELEM)
    nodes = random_nodes(NB_ELEM)
    for item in nodes:
        try:
            ns.remove(item)
        except KeyError:
            pass
```

Anyway I found an easy solution for this specific case (may not apply to RangeSetND though).


It is more difficult to see the problem with RangeSet directly.. this is a bit weird indeed, but this kind of code snippet shows a small performance difference:
```py
def random_range(count, upper=10000):
    return RangeSet(int(random.uniform(1, upper)) for _ in range(1, count))

r1 = random_range(1)
r2 = random_range(NB_ELEM)
for i in range(10000):
    try:
        r1.difference_update(r2, strict=True)
    except KeyError:
        pass
```

**Comment by degremont** [comment]
On my testbed, I had a big performance difference (+400%). 

I confirm the regression is gone using patch from https://review.gerrithub.io/c/373687/ 👍
