### ISSUE TITLE
No host wildcard / asterisk ( * ) support?

### ISSUE THREAD

**Issue by f3flight** [cea-hpc/clustershell#349]
I feel like I'm missing something but it looks like I cannot use clush like so:
`clush -w '*abc*' uptime`

I've set up groups.conf to get a list of hosts from my .ssh/config

I can get a list of all nodes via `nodeset -LL`

Is it true that this is not supported? I am looking for a tool which is able to do this, do you know any?

**Comment by degremont** [comment]
Related to #236

**Comment by degremont** [comment]
#236 is very similar but is using psdh-compatible regexp matching. I prefer this globbing style matching is done first (when this will be implemented, the pdsh-style matching should be easy to do).

This should be done in NodeSet module. It will be automatically supported by clush then

**Comment by thiell** [comment]
@f3flight host wildcard support just landed and will be available in the upcoming 1.8 release. Thanks for this ticket.
