### ISSUE TITLE
Limit concurrent connections

### ISSUE THREAD

**Issue by f3flight** [cea-hpc/clustershell#350]
Is there a way to limit concurrent ssh connections for batch mode? Sometimes it's not possible to spawn many connections at the same time (for ex. some smart firewall, etc.)
Is this feature implemented? If not, this bug can be used as a feature request.

**Comment by thiell** [comment]
@f3flight you're probably looking for `-f n` or `--fanout n`, _n_ being the number of concurrent ssh connections. It's useful either to limit the number of connections to a specific service, for example that won't accept many connections (like puppet), but also for sequential execution (`-f1`).

Example of sequential execution with clush:

```
$ clush -w @compute -f 1 date +%s%N
```

The default fanout can be set in `/etc/clustershell/clush.conf`.

Looking at the [doc](http://clustershell.readthedocs.io/en/latest/tools/clush.html?#fanout-considerations), I guess it would be nice to improve it, so I will keep this ticket open for now.
