### ISSUE TITLE
Python 3 on macOS/BSDs: Clush and library fails with no timeout

### ISSUE THREAD

**Issue by volans-** [cea-hpc/clustershell#353]
I wanted to test the latest release to start migrating my tool to Python 3 (thanks a lot for adding Py3 support!) and found that both `clush` and `ClusterShell` as a library fails on `macOS` (and other BSDs) when not setting a timeout, with `ERROR: [Errno 22] Invalid argument`.

After digging a bit I discovered that:
- in Python 3 the `Engine.Factory.PreferredEngine` factory returns an `EnginePoll` on macOS, while on Python 2 it was returning an `EngineSelect` because `poll()` was not supported.
- when polling for events in `Engine.Poll.EnginePoll.runloop()`, the timeout passed to the `poll.poll()` method is `timeo * 1000.0 + 1.0`, and when the timeout is not specified, `timeo = -1`, hence the passed timeout is `-999.0`.
- Python passes the timeout parameter of `select.poll.poll([timeout])` basically as-is down to the `poll()` system call
- On macOS and other BSDs the `poll()` system call throws an error on arbitrary negative values. Only non-negative integers and `-1` (or the value of `INFTIM` if defined) are accepted.

I've already opened an issue to Python [1] and sent a PR to hopefully fix it [2], but I'll follow up with a PR to ClusterShell too to workaround this issue passing directly `-1` to the `poll()` method.

[1] https://bugs.python.org/issue31334
[2] python/cpython/pull/3277

**Comment by thiell** [comment]
@volans- thanks for the detailed issue, the PR and for the feedback to the Python community!

This problem is also present in Python 2 on the latest FreeBSD 11.1:
```
$ python2
Python 2.7.13 (default, Aug 15 2017, 01:13:59) 
[GCC 4.2.1 Compatible FreeBSD Clang 3.8.0 (tags/RELEASE_380/final 262564)] on freebsd11
Type "help", "copyright", "credits" or "license" for more information.
>>> import select
>>> p = select.poll()
>>> p.poll(-2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
select.error: (22, 'Invalid argument')
```

Looks like they added support for `poll()` there too.

I also noticed other errors with `clush` on this OS, but that's off-topic.

**Comment by volans-** [comment]
@thiell thanks for the additional info, I'll look into it. If/when I'll get some answer on the python issue I'll ask also to backport it.

On a side note, have you considered to use the [`selectors`](https://docs.python.org/3/library/selectors.html) module for the polling?
It should allow to simplify a lot the polling-related code given that it abstracts the different polling systems, doing something similar of what was done here.
It looks like there are two Python 2 backward-compatible modules available: [`selectors2`](https://pypi.python.org/pypi/selectors2) and [`selectors34`](https://pypi.python.org/pypi/selectors34).
I didn't check if it covers all the use cases ClusterShell needs, so it's possible that the direct use of the lower level modules is still needed anyway.

**Comment by thiell** [comment]
@volans- this looks interesting! thanks for the info, especially that it is part of the Standard Python library in 3.4+. There wasn't such thing when we started the project. Because ClusterShell is a base framework primarily targeting HPC clusters, we have to support relatively "old" operating systems, like RHEL6 for instance, with Python 2.6. Unfortunately, I can't find any python package for `selectors` in EPEL 6 or 7.

I would say we keep that in mind and when the time comes (eg. when we're all running Python 3 and about to deprecate 2.7), let's try to re-implement the Engine with `selectors`.

**Comment by volans-** [comment]
@thiell sounds like a plan!

Right, I didn't check distro-packaging, but I guess that could probably be easily solvable, in case you would like to go in that direction sooner with `selectors2` that seems to support Python 2.6.

I agree that the standard library option with Python 3.4+ and no external dependency is cleaner and easier, given that the current code works fine, so no hurry.
