### ISSUE TITLE
string folding / unfolding [question]

### ISSUE THREAD

**Issue by jabbalaci** [cea-hpc/clustershell#384]
I found this project because I needed string folding / unfolding, i.e. convert "node[1-3]" to a list of strings (["node1", "node2", "node3"]) and vice versa. Actually, I needed it for URLs.

I included ClusterShell in my project but I figured out later that it doesn't exist for Windows :( And I develop a cross-platform software. Could someone, who knows well ClusterShell from inside, give me a hint how I could extract just the string (un)folding part? Or do you know a project that can do this advanced string manipulation?

Thanks.

**Comment by jabbalaci** [comment]
I've found the answer. For string folding / unfolding, we need these 4 files only:

* Defaults.py
* NodeSet.py
* NodeUtils.py
* RangeSet.py

They also work under Windows for string (un)folding.

**Comment by thiell** [comment]
Hi @jabbalaci -
Yes this part of the code is localized to these modules, you did well. Are you using some kind of Python package manager on Windows like pip? If so, would it help if ever we decided to separate this part under a clustershell-nodeset subpackage that could be installed without the rest?

**Comment by jabbalaci** [comment]
Hi,
Thanks for the answer. Yes, I tried to install it with pip. The problem was here: https://github.com/cea-hpc/clustershell/blob/805dd0c57cafd3be4c492784595a61334f9c2e85/setup.py#L26 , `os.geteuid()` doesn't work under Windows.
Well, a platform-independent separate package that would do string (un)folding would be useful. As I said, I don't do Linux clustering at all. However, your string (un)folding implementation works well with general strings too, thus this part could be generalized and put into a sub-package.

**Comment by jabbalaci** [comment]
@degremont : it's also a good solution. There's no need to slice the project.

**Comment by degremont** [comment]
@jabbalaci Could you confirm that, if you remove the ``os.getuid()`` call in `setup.py` you can successfully install ClusterShell through pip on windows, and use NodeSet class?

**Comment by jabbalaci** [comment]
@degremont : I tried that and it works like that under Windows. That is, I removed the `os.getuid()` call and left only `CFGDIR = 'etc/clustershell'`. Then I could install under Windows and use the NodeSet class.
