### ISSUE TITLE
Silent error on Python version mismatch with gateway

### ISSUE THREAD

**Issue by demurgos** [cea-hpc/clustershell#388]
Hi,
I am using the ClusterShell Python API from a Python virtual environment using Python 3. It means that my executable is `./venv/bin/python`.

Due to [the way the gateway command is built](https://github.com/cea-hpc/clustershell/blob/805dd0c57cafd3be4c492784595a61334f9c2e85/lib/ClusterShell/Worker/Tree.py#L171), it causes the gateway to use the `python` global executable which corresponds to Python 2.

Beyond this issue of selecting the right executable, there is another problem. The messaging format is dependent on the Python version (it uses `pickle` internally) so having a different Python version at the gateway causes breakage. But there is no raised exception or triggered event: the task just silently stops  and the process exits. I am not aware of any possibility to detect this issue using the ClusterShell API.

My current workaround is to set the global environment variable `CLUSTERSHELL_GW_PYTHON_EXECUTABLE` to `python3` but it breaks encapsulation.

I'd like a way to pass the gateway configuration option to the worker and detect encoding/decoding errors when communicating with the gateway in a reliable way.

**Comment by degremont** [comment]
Hi,

I can understand the need to specify a specific remote executable. We could improve TreeWorker API for that. 

Regarding error detection, which version of CS are you using? There is some improvements in detecting bad gateways in latest `master`, which will be released in CS 1.8.1.
I'm not sure, but this could possible help you.

**Comment by demurgos** [comment]
An additional argument to the TreeWorker API for the Python executable would help me in this case.

I encountered the silent errors when the root node used CS 1.8 for Python 3 while the gateway only had CS 1.7.1 for Python 2. I solved my issue by installing CS 1.8 for Python 3 on the gateway and setting the environment variable at the root.
I did not try the latest 1.8.1 release.

**Comment by degremont** [comment]
Indeed, gateways *should* use the same Python and ClusterShell version than the master node.

Need to check if 1.8.1 reports a proper error message if this is not the case.

**Comment by demurgos** [comment]
FYI, the latest published version on Pypi and EPEL is still `1.8`. Does `1.8.1` refers to the current `master` branch on Github?

**Comment by degremont** [comment]
Yes. `1.8.1` is not yet released but will be soon. This is very close to current `master` code.
