### ISSUE TITLE
Using multiline shell variables in options

### ISSUE THREAD

**Issue by kcgthb** [cea-hpc/clustershell#394]
Using multiline variables works for commands, but not for options.

For instance, folding works:
```
$ foo="foo1
> foo2
> foo3"
$ cluset -f $foo
foo[1-3]
```

But it doesn't work when multiline variables are passed as options:
```
$ cluset -f foo[1-4] -x "$foo"
foo[1-4]
```
Expected result:
```
$ cluset -f foo[1-4] -x "$foo"
foo4
$ cluset -f foo[1-4] -x "foo[1-3]"
foo4
```

**Comment by thiell** [comment]
a patch for this is being reviewed at https://review.gerrithub.io/c/cea-hpc/clustershell/+/431249
