### ISSUE TITLE
Install instructions on EMR

### ISSUE THREAD

**Issue by AbdealiJK** [cea-hpc/clustershell#397]
https://clustershell.readthedocs.io/en/latest/install.html this page has been immensely helpful for me to get clush installed easily. But the one place I still cant get clush installed with ease is the amazon EMR clusters ...

If I spawn an EMR cluster, it does have epel - but they have their own version of epel and that doesnt seem to have clustershell in it.
Would be awesome if instructions for EMR are added here for folks like me.

**Comment by degremont** [comment]
We are not EMR specialist at all. We have never used EMR. Could you help us?

**Comment by AbdealiJK** [comment]
@degremont Thanks for looking into this. A day after I reported this, I realized that clustershell is actually available on pypi - https://pypi.org/project/ClusterShell/
I seem to have missed https://clustershell.readthedocs.io/en/latest/install.html#install-pip-user as I kept looking for an RPM considering that Amazon Linux was original based on Red Hat and is Redhat binary compatible.

This issue could be possibly closed, as the documentation is sufficient and I should have realized I should fallback to `pip` if the RPM was unavailable.
Alternatively, the documentation could be modified to explicitly state that for Amazon Linux, `pip` should be used as there is no binary available in the system packages (considering amazon is a fairly popular devops option)

**Comment by degremont** [comment]
ClusterShell is available in EPEL, and Amazon Linux has an easy access to EPEL.
I think the simplest way is simply to enable EPEL in your EC2 instance. 

https://aws.amazon.com/premiumsupport/knowledge-center/ec2-enable-epel/

This looks like:
```
sudo amazon-linux-extras enable epel
sudo yum install -y epel-release
sudo yum install -y clustershell
```

https://aws.amazon.com/amazon-linux-2/faqs/#Amazon_Linux_Extras

**Comment by AbdealiJK** [comment]
Was just doing some stuff on Amazon again today and came back to this thread.
`sudo amazon-linux-extras enable epel` is for Amazon Linux 2. EMR does not use AmazonLinux2 ... it still uses AmazonLinux1

Seems like pip it is for EMR

**Comment by degremont** [comment]
This is even simpler with AL1.
```
sudo yum install --enablerepo=epel -y clustershell
```

How to enable EPEL for AL1 was already explained the documentation link above from AWS.

**Comment by AbdealiJK** [comment]
I feel really dumb :D
Weird. I seem to have had this strong opinion that EPEL was not available and spent hours trying to find workarounds ...
This is great. Thanks !
