### ISSUE TITLE
config option for default folding --axis

### ISSUE THREAD

**Issue by thiell** [cea-hpc/clustershell#401]
It would be convenient to have a way to set a default --axis for `clush` and `cluset`/`nodeset`.

`--axis=-1 is` often to be used when interacting with Slurm due to some node set parsing limitation.
Investigate if we should use `defaults.conf` (at the library level) and/or have an environment variable to enforce a default folding axis.
One concern with this approach would be that the same `cluset`/`nodeset` or `clush` command performed on systems with different `defaults.conf` could lead to different results (well, not actually different but formatted differently).

**Comment by thiell** [comment]
See also https://bugs.schedmd.com/show_bug.cgi?id=4138

**Comment by thiell** [comment]
https://review.gerrithub.io/c/cea-hpc/clustershell/+/462003

**Comment by thiell** [comment]
Oh I actually think it's a duplicate of #356 !

**Comment by degremont** [comment]
Probably to track this patch under #356 for a better history, and close this one as duplicate?
