### ISSUE TITLE
nodeset -f *

### ISSUE THREAD

**Issue by thierrybarrier1** [cea-hpc/clustershell#411]
Using the clustershell command, with 1.7 release (clustershell-1.7.1-1.el7.noarch), the following command give the following result :
# nodeset -f '*'
*

But using the new 1.8 clustershell release (clustershell-1.8-1.el7.noarch.rpm) : 
# nodeset -f '*'
example[4-6,32-159]

which is not really an expected output, looks more like an example !!!

**Comment by degremont** [comment]
The default clustershell setup comes with an example list with this specific group content in it.

Just check `/etc/clustershell*` and your clustershell setup. It seems you are using the example config and the one you are expecting.

**Comment by thiell** [comment]
Hi @thierrybarrier1,

clustershell 1.8 introduced node wildcard support, as documented in https://clustershell.readthedocs.io/en/latest/tools/nodeset.html#node-wildcards

so that now, `nodeset -f '*'` is equivalent to `nodeset -f @all`

You see `example[4-6,32-159]` because the  RPM installs a default group configuration (local) in /etc/clustershell/groups.d/local.cfg (where a cluster named _example_ is defined). See also https://clustershell.readthedocs.io/en/latest/config.html#groups-config for more information about clustershell groups.

**Comment by thierrybarrier1** [comment]
Hi Aurelien,

how do you explain that 1.7 is returning * so ?
I use exactly the same env, 1 time using 1.7, 1 time using 1.8.

I can see using 1.7, that I have a local.cfg (effectively with example in it) under /etc/clustershell/groups.d
However, with this 1.7, nodeset -f '*' retruns *


Thanks
Thierry
________________________________

**Comment by degremont** [comment]
I was assuming you did not use the exact same environment between both versions and were tricked by the update.
But the exact answer was done by @thiell . See his reply.

**Comment by thierrybarrier1** [comment]
Hi

this "new feature" breaks the compatibility, impacting one of our tools (hmtool).
Just pointed out this difference of behavior:

1.7
nodeset -f '*' => *
nodeset -f @all => example[4-6,32-159]

1.8
nodeset -f '*' => example[4-6,32-159]
nodeset -f @all => example[4-6,32-159]

Never a good idea to break compatibility, even for providing new feature (should be at least in a major release !)

However for us this is not a big deal, we will modify our tool accordingly.

Thanks
Thierry

________________________________

**Comment by thiell** [comment]
@thierrybarrier1 I'm glad that you will be able to modify your tool to work around the issue, I hope it won't be too much of a hassle.

We're VERY careful of the backward compatibility overall with clustershell. Also, we do encourage users to test the master branch and report compatibility issues before official releases. Reported compatibility issues will be highly prioritized.

While I fully understand your concern in this specific case, I don't consider it a real compat issue. Please note that `nodeset` aims to primarily manipulate **cluster node names**, and `*` and `?` have never been valid characters for cluster node names. The manual states the following:

>[nodeset/cluset] provides easy manipulation of 1D or nD-indexed cluster nodes and node groups and supports RFC 1123.

Version 1.8 (released in October 2017) added support for `*` and `?` as wildcard. While it is possible to disable this feature with the Python library, it is not possible using the CLI. Perhaps we should add that feature.

We are aware that a lot of users now uses `NodeSet` or `nodset/cluset` to manipulate any kind of strings, so I do understand the problem, but almost two years after the 1.8 release, it is unfortunately too late to go back at this point.

Finally, I don't know your tool hmtool, but I'm curious, any pointers would be welcomed. :)
Thanks again for the report.

**Comment by thierrybarrier1** [comment]
Hi,

Thanks for your answer, and once again not a big deal for us.
I fill the issue just in case this could be a serious one.
If you fill this is finally not a real issue, but more a "new functionality", well that s OK for me.
In such a case, I guess you can close the issue

Thierry

PS: hmtool is an internal tool for HPC clusters, allowing to generate configuration for HPC clusters.

________________________________
