### ISSUE TITLE
Tree-mode doesn't work with multi-hop gateways

### ISSUE THREAD

**Issue by janoliver** [cea-hpc/clustershell#419]
Hi ClusterShell devs, first off: Thank you for your work and for open sourcing it!

I'm trying to test ClusterShell on a relatively big HPC infrastructure; we have a number of c3 clusters, each of which consists of a number of racks. It seems natural to use the tree mode for clush here. We'd like to run clush from our workstations, which are not part of the cluster. 

Let's assume that my workstation is called `ws`, the login node of the cluster is called `login`, and we want to run commands on node `005` of cluster `31`. The head node of the rack where `005` is in is node `001`. My `topology.conf` file now looks like this:
```
[routes]
ws: login
login: sc31n001
sc31n001: sc31n005
```
ClusterShell is reachable on every node via `CLUSTERSHELL_GW_PYTHON_EXECUTABLE`. 

Now, when I run `clush -w sc31n001 date`, I'm getting the correct response. However, `clush -w sc31n005 date` hangs. The debugging output is:
```
DEBUG:root:clush: STARTING DEBUG
Warning: fd_max set to 8192 but max open files hard limit is 4096
Changing max open files soft limit from 1024 to 4096
User interaction: True
Create STDIN worker: False
clush: enabling tree topology (2 gateways)
clush: nodeset=sc31n005 fanout=64 [timeout conn=10.0 cmd=0.0] command="date"
---------------
ws
`- login
   `- sc31n001
      `- sc31n005
---------------
DEBUG:ClusterShell.Worker.Tree:stderr=True
DEBUG:ClusterShell.Worker.Tree:TreeWorker._launch on sc31n005 (fanout=64)
DEBUG:ClusterShell.Worker.Tree:next_hops=[('login', 'sc31n005')]
DEBUG:ClusterShell.Worker.Tree:trying gateway login to reach sc31n005
DEBUG:ClusterShell.Worker.Tree:_execute_remote gateway=login cmd=date targets=sc31n005
DEBUG:ClusterShell.Task:pchannel: creating new channel <ClusterShell.Propagation.PropagationChannel object at 0x7f40199e9350>
SSHCLIENT: ssh -oForwardAgent=no -oForwardX11=no -oConnectTimeout=10 -oBatchMode=yes login CLUSTERSHELL_GW_LOG_DIR=/tmp/clustershell_example CLUSTERSHELL_GW_LOG_LEVEL=DEBUG /ptmp/tzw0am1/clustershell/venv/bin/python -m ClusterShell.Gateway -Bu
DEBUG:ClusterShell.Engine.Engine:set_events: client <ClusterShell.Engine.EPoll.EngineEPoll object at 0x7f4019c82910> not registered
DEBUG:ClusterShell.Engine.Engine:set_events: client <ClusterShell.Engine.EPoll.EngineEPoll object at 0x7f4019c82910> not registered
DEBUG:ClusterShell.Engine.Engine:set_events: client <ClusterShell.Engine.EPoll.EngineEPoll object at 0x7f4019c82910> not registered
DEBUG:ClusterShell.Engine.Engine:set_events: client <ClusterShell.Engine.EPoll.EngineEPoll object at 0x7f4019c82910> not registered
DEBUG:ClusterShell.Engine.Engine:set_events: client <ClusterShell.Engine.EPoll.EngineEPoll object at 0x7f4019c82910> not registered
DEBUG:ClusterShell.Propagation:shell nodes=sc31n005 timeout=-1 worker=139913284406608 remote=True
DEBUG:ClusterShell.Propagation:send_queued: 0
DEBUG:ClusterShell.Worker.Tree:TreeWorker: _check_ini (0, 0)
login: <?xml version="1.0" encoding="utf-8"?>
login: <channel version="1.8.2"><message ack="0" msgid="2" type="ACK"></message>
DEBUG:ClusterShell.Propagation:recv: Message CHA (msgid: 2, type: CHA)
DEBUG:ClusterShell.Propagation:channel started (version 1.8.2 on remote gateway)
DEBUG:ClusterShell.Propagation:recv: Message ACK (ack: 0, msgid: 2, type: ACK)
DEBUG:ClusterShell.Propagation:recv_cfg
DEBUG:ClusterShell.Propagation:CTL - connection with gateway fully established
DEBUG:ClusterShell.Propagation:dequeuing sendq: Message CTL (srcid: 139913284406608, msgid: 1, type: CTL, action: shell, target: sc31n005)
login: No handlers could be found for logger "ClusterShell.Gateway"
login: <message ack="1" msgid="6" type="ACK"></message>
DEBUG:ClusterShell.Propagation:recv: Message ACK (ack: 1, msgid: 6, type: ACK)
DEBUG:ClusterShell.Propagation:got ack (ACK)
```

After that, it waits indefinitely. Any idea what's going wrong here?

**Comment by degremont** [comment]
Thanks for your support! We appreciate it!

Could you test your command from host `login`? And if this is also failing, could you give us the command debugging output?

**Comment by thiell** [comment]
@janoliver could you also provide gateway debug logs from `login` and `sc31n001` found in `$CLUSTERSHELL_GW_LOG_DIR ` (apparently `/tmp/clustershell_example` in your case)

Please also check that real hostnames do match node names in topology.conf

**Comment by janoliver** [comment]
@thiell, thanks for the hint. On the `login` node, I can see the following output in the debug log: 
```
2019-09-16 11:43:29,860 ClusterShell.Gateway DEBUG SSHCLIENT: ssh -oForwardAgent=no -oForwardX11=no -oConnectTimeout=10 -oBatchMode=yes sc31n001 CLUSTERSHELL_GW_LOG_DIR=/tmp/clustershell_example CLUSTERSHELL_GW_LOG_LEVEL=DEBUG python -m ClusterShell.Gateway -Bu
...
2019-09-16 11:43:30,277 ClusterShell.Gateway DEBUG sc31n001: /usr/bin/python: No module named ClusterShell
```
Apparently, the `CLUSTERSHELL_GW_PYTHON_EXECUTABLE` environment is not correctly communicated/used on the jump hosts. Is that a bug?

**Comment by degremont** [comment]
After a quick look into the code it seems you're right. 

Could you try adding this variable `CLUSTERSHELL_GW_PYTHON_EXECUTABLE` to the list of variables `Tree.py` in https://github.com/cea-hpc/clustershell/blob/master/lib/ClusterShell/Worker/Tree.py#L161? And test again.

**Comment by janoliver** [comment]
Sure, that looks right. I'll try it tomorrow at work.

In any case, it seems like error handling is not really existing for tree mode, as the whole thing just hangs when something doesn't work. Would it be hard to add some?

**Comment by janoliver** [comment]
It works with @degremont's suggestion. Thank you!

**Comment by degremont** [comment]
Glad it works! Thanks for the report, we will see how to improve that!
