### ISSUE TITLE
clush copy does not support ipv6

### ISSUE THREAD

**Issue by huanghui3** [cea-hpc/clustershell#424]

**Comment by huanghui3** [comment]
clush -w 192:168:32::ad22 --copy test --dest /tmp/
192:168:32::ad22: ssh: connect to host 0.0.0.192 port 22: Invalid argument
192:168:32::ad22: lost connection
clush: 192:168:32::ad22: exited with exit code 1

**Comment by degremont** [comment]
Thanks for your report.
Could you run and provide the output of the same command with `-v -d`?
Could you do the same with 
`clush -v -d -w 192.168.32::ad22 echo ok` ?

**Comment by martinetd** [comment]
Aurélien Degrémont wrote on Mon, Jan 13, 2020 at 11:57:42PM -0800:
> Could you run and provide the output of the same command with `-v -d`?
> Could you do the same with 
> `clush -v -d -w 192.168.32::ad22 echo ok` ?

That works, the problem is just missing brackets for scp e.g. an ipv6
should be user@[ipv6]:file not user@ipv6:file

it looks like we can just always put brackets (e.g. user@[ipv4]:file or
user@[domain]:file work), so that's an easy fix

**Comment by degremont** [comment]
Indeed that should be an easy fix. That only needs to fix the command in `Ssh.py` and maybe some tests that checks the syntax but I'm not even sure there are some. @huanghui3 could you verify this fix your issue?

**Comment by martinetd** [comment]
You can try https://review.gerrithub.io/c/cea-hpc/clustershell/+/481573

(others: please test on older systems as well, I only tried on a fedora
31 so it's possible older scp don't allow the syntax)

**Comment by huanghui3** [comment]
clush comand is ok ,copy does not work. It should be   user@[ipv6]:file not user@ipv6:file

clush -v -d -w 192:168:32::ad22 --copy test --dest /tmp/
clush: nodeset=192:168:32::ad22 fanout=64 [timeout conn=10.0 cmd=0.0] copy sources=['test'] dest=/tmp/
SCP: scp -oConnectTimeout=15 -oBatchMode=yes test 192:168:32::ad22:/tmp/
192:168:32::ad22@STDERR: ssh: connect to host 0.0.0.192 port 22: Invalid argument

**Comment by degremont** [comment]
@huanghui3 see @martinetd 's comment

**Comment by degremont** [comment]
> (others: please test on older systems as well, I only tried on a fedora 31 so it's possible older scp don't allow the syntax)

Looks like OpenSSH is supporting this standard syntax for years. 

Tested on `openssh-7.4p1-16.85.al12.x86_64` (RHEL 7): **OK**
