### ISSUE TITLE
clush -w command changes hostname

### ISSUE THREAD

**Issue by huanghui3** [cea-hpc/clustershell#425]
The hostname is c1. After the clush command is executed, it becomes c01.
 clush -w c1,c02 ls
c01: ssh: Could not resolve hostname c01: Name or service not known
clush: c01: exited with exit code 255
c02: ssh: Could not resolve hostname c02: Name or service not known
clush: c02: exited with exit code 255

**Comment by martinetd** [comment]
This is a duplicate of #293 -- closing
