### ISSUE TITLE
about Zero-padding and issue #293

### ISSUE THREAD

**Issue by huanghui3** [cea-hpc/clustershell#427]
I have read all the replies related to issue #293 .
In this scenario, whether we can keep the original host name without adding or removing 0?
This scenario is very common.
eg some nodes are named :c01,c02...c09,c010.... If we use the clush command, c010 is changed to c10.
clush -w c09,c**010** ls
clush: c09: exited with exit code 255
clush: **c10**: exited with exit code 255

**Comment by degremont** [comment]
Hello @huanghui3

Your problem is exactly what's tracked under ticket #293. There is no other workaround available as far as I known. 
For now, ClusterShell does not support mixing hostname with different paddings in the same command.
