### ISSUE TITLE
CLI_COLOR support

### ISSUE THREAD

**Issue by kcgthb** [cea-hpc/clustershell#428]
Hi!

To build on #334 and #390, would it be possible to add support for `NO_COLOR` (https://no-color.org/) in ClusterShell?

**Comment by degremont** [comment]
I think CLI_COLOR would have more value there (https://bixense.com/clicolors/)

**Comment by kcgthb** [comment]
What about supporting both?

**Comment by dupgit** [comment]
Hi,
I propose PR #432 to solve this Issue. It implements both NO_COLOR and CLI_COLOR that has different purposes.
Regards,
Olivier.
