### ISSUE TITLE
Use clush OutputHandlers in external tools

### ISSUE THREAD

**Issue by mattaezell** [cea-hpc/clustershell#433]
`clush` has a rich set of output handlers defined in `Clush.py`.  Instead of reimplement them for an external tool, it would be nice to be able to use them directly.  Unfortunately, the error messages currently hard-code `clush:` as a prefix.

I would propose making the prefix configurable, and potentially moving the `OutputHandler`s into either `Display.py` or their own new file.

I'm happy to implement and open a PR, but I wanted to get some consensus before starting work.  Thoughts?

**Comment by degremont** [comment]
Distributing official handler helper classes is something we have in mind for a while, but never took time to do.

I see no issue with updating the error message prefix to help use re-use them. This could easily go into a 1.8.4. 
Making them officially in a separate packages mean we will have to support them as-is for a while and I'm not fond of doing that without doing a bit of cleaning and maybe improvements.

**Comment by degremont** [comment]
Thanks @mattaezell for the PR. Overall the patch looks good and clean.

We were discussing of the interest of moving the classes in a dedicated file. Could you explain which classes you are interested in and how you want to use them? That would be useful for us to decide how these classes could go public.

**Comment by mattaezell** [comment]
Our current use case for the output handlers is a tool that manages power state of nodes (what is the current power state, turn nodes on/off).  If there are 10 or fewer nodes, it uses `DirectProgressOutputHandler`, and over 10 it switches to `GatherOutputHandler`.
