### ISSUE TITLE
NodeSet: Create a node mask from task.iter_buffers

### ISSUE THREAD

**Issue by lmagdanello** [cea-hpc/clustershell#440]
Hi guys. I was creating a small script to check some nodes and I needed to create a node mask (like node [0-100,103,105-200]), but I realized that NodeSet was not able to create this mask from the iteration I was doing because of the type of variable nodes ... I had the following approach, then:

```
for buf, nodes in task.iter_buffers():
    if buf == 'Permissive':
       mask_nodes = NodeSet(','.join(str(n) for n in nodes))
```

I wonder if there is an easier way to do it. 
Perhaps transforming the type of nodes into the for itself? Or if NodeSet itself is already capable of doing so...

Thx! 😄

**Comment by degremont** [comment]
I think you want:

```
for buf, nodes in task.iter_buffers():
    if buf == 'Permissive':
       mask_nodes = NodeSet.fromlist(nodes)
```

Have a look at online doc https://clustershell.readthedocs.io/en/latest/api/Task.html#ClusterShell.Task.Task.iter_buffers or using `pydoc ClusterShell.Task.iter_buffers`

**Comment by lmagdanello** [comment]
Thx! Exactly what I needed. 😄
