### ISSUE TITLE
Release v1.9 on pypi has empty /tests/TLib.py?

### ISSUE THREAD

**Issue by bjornfor** [cea-hpc/clustershell#509]
AFAICT, the latest release on pypi has an empty /tests/TLib.py file, breaking the tests:

```
ERROR: test YAMLGroupLoader cache_time
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/ClusterShell-1.9/tests/NodeSetGroupTest.py", line 1538, in test_reload
    f = make_temp_file(dedent("""
NameError: name 'make_temp_file' is not defined
```

Compare https://files.pythonhosted.org/packages/47/32/86c133128f0904fd5b11b8df184456aad83d65cb3a74491bb784c0ca6ca2/ClusterShell-1.9.tar.gz with https://github.com/cea-hpc/clustershell/archive/refs/tags/v1.9.tar.gz where you should see that /tests/Tlib.py is empty in the pypi archive and is 4.8 KiB in the github archive.

EDIT: Oops, I accidentally pressed submit before I had finished writing the issue.

**Comment by thiell** [comment]
Thanks for pointing that out. This is weird indeed, I am not sure why. But I can see an empty TLib.py locally after a `python setup.py sdist`. But if I do it again, TLib.py is not empty anymore. WEIRD... Anyway, I cannot override pypi's tar.gz, it is not allowed. We'll have to change the version to fix this.
