### ISSUE TITLE
location of yaml file

### ISSUE THREAD

**Issue by iomari** [cea-hpc/clustershell#516]
Greetings,
I'm having trouble locating the proper folder to put my yaml file in my home folder.
The one I created in /etc/clustershell/groups.d/ works but when I move it to ~/.clusterssh/ or ~/.clusterssh/groups.d/ I can no longer use groups with clush.

**Comment by degremont** [comment]
Hi @iomari 

This is indeed not a surprise as you're using `clustershell` and not `clusterssh` :)

See https://clustershell.readthedocs.io/en/latest/config.html#groups-conf for all details about how to configure `groups.conf` and related files.
