### ISSUE TITLE
OpenSuse Leap 15.3+ support

### ISSUE THREAD

**Issue by oxedions** [cea-hpc/clustershell#517]
Hello clustershell team, 🙂 

I am working on the BlueBanquise stack (https://github.com/bluebanquise/), and since the stack heavily relies on clustershell python modules, I noticed when upgrading a cluster that starting from OpenSuse Leap 15.3 and more, there are no more clustershell official packages for Suse (https://software.opensuse.org/package/clustershell).

Do you know what happen and if there is a plan to include clustershell again in OpenSuse Leap / SLES ?

**Comment by thiell** [comment]
Hi @oxedions,
We always love to hear about other projects making good use of clustershell!
So re: OpenSUSE, while we help maintaining clustershell in Tumbleweed, we're not maintainer in Leap. I asked @e4t for help and it has been submitted: https://build.opensuse.org/request/show/1059294 

We're not maintainer of clustershell in Leap but I asked them

**Comment by oxedions** [comment]
Dear @thiell ,

Many thanks for this feedback and actions taken !
I understand, and I will wait that package is released for 15.4 or next version.
In the meantime, I will document to rely on pip3 to grab clustershell when using SLES/Leap 15.4.

Have a nice end of week ! 😉
