### ISSUE TITLE
License clarity in package metadata

### ISSUE THREAD

**Issue by edef1c** [cea-hpc/clustershell#522]
The source code quite clearly specifies LGPLv2.1+, and that appears to be what contributors agreed to in https://github.com/cea-hpc/clustershell/issues/321. However, the `setup.py` specifies "License :: OSI Approved :: GNU Lesser General Public License v2 or later (LGPLv2+)", equivalent to `LGPL-2.0-or-later`, which is liable to lead to confusion and mistakes with automated compliance tools.

PyPI does not appear to provide a classification equivalent to `LGPL-2.1.or-later`, so this leaves us in a bit of a bind.

**Comment by thiell** [comment]
In my understanding, "License :: OSI Approved :: GNU Lesser General Public License v2 or later (LGPLv2+)" is NOT equivalent to `LGPL-2.0-or-later`. Indeed [LGPL 2.0](https://www.gnu.org/licenses/old-licenses/lgpl-2.0.en.html) was called GNU **Library** General Public License 2.0. We use term "GNU **Lesser** General Public License v2 or later", which should imply `LGPL 2.1-or-later`.

**Comment by edef1c** [comment]
My bad, thank you. Looks like I'm barking up the wrong tree, then.
