### ISSUE TITLE
broken link in docs link to llnl.gov pdsh page

### ISSUE THREAD

**Issue by ryantig** [cea-hpc/clustershell#551]
broken link in docs: https://clustershell.readthedocs.io/en/latest/tools/clush.html#id2
broken link points to: https://computing.llnl.gov/linux/pdsh.html
I suggest linking to https://software.llnl.gov/repo/#!/chaos/pdsh
Submitted pull request for edit: https://github.com/cea-hpc/clustershell/pull/550

**Comment by thiell** [comment]
@ryantig thanks! We will also update the corresponding man page for the next release.
