### ISSUE TITLE
Add kqueue based Engine

### ISSUE THREAD

**Issue by thiell** [cea-hpc/clustershell#9]
Add new engine implementation based on kqueue for use with BSD: ```ClusterShell.Engine.KQueue```, based on http://docs.python.org/library/select.html?highlight=kqueue#select.kqueue select.kqueue() (new in Python 2.6).

**Comment by degremont** [comment]
@thiell : Should we consider this ticket as ``wontfix``?
It has been opened for ages and will probably never been implemented.
BSD supports ```poll()``` which already has good performances and I do not see the use case where ``kqueue()`` could really benefit to BSD systems.

Let somebody open a new one if it really see an interest for that.

**Comment by thiell** [comment]
I agree - reopen if needed. I've no time to maintain a kqueue engine and AFAIK most clustershell users are using Linux so `epoll_wait()`, otherwise if `poll()` is available it's still better than `select()`.
